# Generated by Django 5.2.16 on 2026-08-01 02:40
# ruff: noqa: E501

import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0003_membership_organizations_membership_org_id_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=150)),
                ("phone_e164", models.CharField(max_length=13)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("phone_call", "Llamada"),
                            ("social_network", "Red social"),
                            ("referral", "Referido"),
                            ("walk_in", "Visita"),
                            ("website", "Sitio web"),
                            ("other", "Otro"),
                        ],
                        max_length=24,
                    ),
                ),
                ("origin_detail", models.CharField(blank=True, max_length=160)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=100)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("event_timezone", models.CharField(max_length=64)),
                ("estimated_guests", models.PositiveIntegerField()),
                ("general_need", models.CharField(max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("phone_call", "Llamada"),
                            ("social_network", "Red social"),
                            ("referral", "Referido"),
                            ("walk_in", "Visita"),
                            ("website", "Sitio web"),
                            ("other", "Otro"),
                        ],
                        max_length=24,
                    ),
                ),
                ("origin_detail", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nueva"),
                            ("quoted", "Cotizada"),
                            ("accepted", "Aceptada"),
                            ("confirmed", "Confirmada"),
                            ("closed_lost", "Perdida"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_reason", models.CharField(blank=True, max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "responsible_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.membership",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_requests",
                        to="commercial.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField()),
                ("full_name", models.CharField(max_length=150)),
                ("phone_e164", models.CharField(max_length=13)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("phone_call", "Llamada"),
                            ("social_network", "Red social"),
                            ("referral", "Referido"),
                            ("walk_in", "Visita"),
                            ("website", "Sitio web"),
                            ("other", "Otro"),
                        ],
                        max_length=24,
                    ),
                ),
                ("origin_detail", models.CharField(blank=True, max_length=160)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="commercial.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visible_number", models.CharField(max_length=24)),
                (
                    "event_request",
                    models.OneToOneField(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation",
                        to="commercial.eventrequest",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuotationSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("next_value", models.PositiveIntegerField(default=1)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuotationVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("request_revision", models.PositiveIntegerField()),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("issued", "Emitida"),
                            ("accepted", "Aceptada"),
                            ("superseded", "Sustituida"),
                            ("withdrawn", "Retirada"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("valid_until", models.DateTimeField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("organization_name_snapshot", models.CharField(max_length=150)),
                ("person_name_snapshot", models.CharField(max_length=150)),
                ("person_phone_snapshot", models.CharField(max_length=13)),
                ("person_email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("event_type_snapshot", models.CharField(max_length=100)),
                ("event_starts_at_snapshot", models.DateTimeField()),
                ("event_ends_at_snapshot", models.DateTimeField()),
                ("event_timezone_snapshot", models.CharField(max_length=64)),
                ("estimated_guests_snapshot", models.PositiveIntegerField()),
                ("general_need_snapshot", models.CharField(max_length=500)),
                ("request_notes_snapshot", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("acceptance_channel", models.CharField(blank=True, max_length=32)),
                ("acceptance_note", models.CharField(blank=True, max_length=500)),
                (
                    "accepted_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_quotation_versions",
                        to="organizations.membership",
                    ),
                ),
                (
                    "issued_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_quotation_versions",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="commercial.quotation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuotationLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=240)),
                ("unit_label", models.CharField(blank=True, max_length=40)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("line_subtotal", models.DecimalField(decimal_places=2, max_digits=18)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "quotation_version",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="commercial.quotationversion",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_interval", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ("event_timezone", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisional", "Provisional"),
                            ("confirmed", "Confirmada"),
                            ("expired", "Vencida"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="provisional",
                        max_length=16,
                    ),
                ),
                ("hold_expires_at", models.DateTimeField()),
                (
                    "confirmation_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("external_deposit", "Anticipo recibido externamente"),
                            ("waiver", "Excepción autorizada"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "recognized_deposit_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("deposit_reported_at", models.DateTimeField(blank=True, null=True)),
                ("deposit_reference", models.CharField(blank=True, max_length=300)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("waiver_reason", models.CharField(blank=True, max_length=500)),
                ("waiver_authorized_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=500)),
                (
                    "cancelled_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_reservations",
                        to="organizations.membership",
                    ),
                ),
                (
                    "confirmed_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_reservations",
                        to="organizations.membership",
                    ),
                ),
                (
                    "event_request",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="commercial.eventrequest",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "quotation_version",
                    models.OneToOneField(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation",
                        to="commercial.quotationversion",
                    ),
                ),
                (
                    "waiver_authorized_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waived_reservation_deposits",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="commercial_person_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("organization", "phone_e164"), name="commercial_person_org_phone_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("full_name", django.db.models.functions.text.Trim("full_name")),
                    models.Q(("full_name", ""), _negated=True),
                ),
                name="commercial_person_name_canonical",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(("phone_e164__regex", "^\\+593(?:[2-7][0-9]{7}|9[0-9]{8})$")),
                name="commercial_person_phone_ec",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "origin__in",
                        [
                            "whatsapp",
                            "phone_call",
                            "social_network",
                            "referral",
                            "walk_in",
                            "website",
                            "other",
                        ],
                    )
                ),
                name="commercial_person_origin_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="commercial_person_revision_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrequest",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="commercial_eventrequest_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("starts_at__lt", models.F("ends_at"))),
                name="commercial_eventrequest_interval_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("estimated_guests__gte", 1)),
                name="commercial_eventrequest_guests_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="commercial_eventrequest_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["new", "quoted", "accepted", "confirmed", "closed_lost", "cancelled"],
                    )
                ),
                name="commercial_eventrequest_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="personrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="commercial_personrevision_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="personrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "person", "revision"),
                name="commercial_personrevision_org_person_rev_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="personrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="commercial_personrevision_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="commercial_quotation_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                fields=("organization", "event_request"), name="commercial_quotation_org_request_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                fields=("organization", "visible_number"), name="commercial_quotation_org_number_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationsequence",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="commercial_quote_sequence_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationsequence",
            constraint=models.UniqueConstraint(
                fields=("organization", "year"), name="commercial_quote_sequence_org_year_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationsequence",
            constraint=models.CheckConstraint(
                condition=models.Q(("next_value__gte", 1)),
                name="commercial_quote_sequence_next_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="commercial_quoteversion_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "quotation", "version"),
                name="commercial_quoteversion_org_quote_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("organization", "quotation"),
                name="commercial_quoteversion_one_draft_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("version__gte", 1), ("request_revision__gte", 1), ("revision__gte", 1)
                ),
                name="commercial_quoteversion_revisions_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "USD")), name="commercial_quoteversion_currency_usd"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal__gte", 0),
                    ("discount_total__gte", 0),
                    ("total__gte", 0),
                    ("discount_total__lte", models.F("subtotal")),
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("subtotal"), "-", models.F("discount_total")
                        ),
                    ),
                ),
                name="commercial_quoteversion_totals_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="commercial_quoteline_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.UniqueConstraint(
                fields=("organization", "quotation_version", "position"),
                name="commercial_quoteline_org_version_position_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("position__gte", 1),
                    ("quantity__gt", 0),
                    ("unit_price__gte", 0),
                    ("discount_amount__gte", 0),
                    ("line_subtotal__gte", 0),
                    ("line_total__gte", 0),
                    ("discount_amount__lte", models.F("line_subtotal")),
                    (
                        "line_total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("line_subtotal"), "-", models.F("discount_amount")
                        ),
                    ),
                ),
                name="commercial_quoteline_amounts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="commercial_reservation_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("organization", "quotation_version"),
                name="commercial_reservation_org_quoteversion_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["provisional", "confirmed"])),
                fields=("organization", "event_request"),
                name="commercial_reservation_one_active_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["provisional", "confirmed", "expired", "cancelled"])
                ),
                name="commercial_reservation_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recognized_deposit_amount__isnull", True),
                    ("recognized_deposit_amount__gt", 0),
                    _connector="OR",
                ),
                name="commercial_reservation_deposit_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status__in", ["provisional", "confirmed"])),
                expressions=[("organization", "="), ("event_interval", "&&")],
                name="commercial_reservation_no_overlap",
            ),
        ),
    ]
