# Generated by Django 5.2.16 on 2026-08-01 04:24

import django.db.models.expressions
import django.db.models.functions.math
from django.db import migrations, models

RESERVATION_COHERENCE_FORWARD = """
CREATE FUNCTION public.claridez_validate_reservation_coherence()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
DECLARE
    expected_request_id uuid;
    expected_interval tstzrange;
    expected_timezone text;
    quotation_status text;
BEGIN
    SELECT
        quotation.event_request_id,
        tstzrange(
            version.event_starts_at_snapshot,
            version.event_ends_at_snapshot,
            '[)'
        ),
        version.event_timezone_snapshot,
        version.status
    INTO
        expected_request_id,
        expected_interval,
        expected_timezone,
        quotation_status
    FROM public.commercial_quotationversion AS version
    JOIN public.commercial_quotation AS quotation
      ON quotation.organization_id = version.organization_id
     AND quotation.id = version.quotation_id
    WHERE version.organization_id = NEW.organization_id
      AND version.id = NEW.quotation_version_id;

    IF NOT FOUND OR quotation_status IS DISTINCT FROM 'accepted' THEN
        RAISE EXCEPTION 'reservation requires an accepted quotation version'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.event_request_id IS DISTINCT FROM expected_request_id THEN
        RAISE EXCEPTION 'reservation request does not match quotation request'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.event_interval IS DISTINCT FROM expected_interval THEN
        RAISE EXCEPTION 'reservation interval does not match quotation snapshot'
            USING ERRCODE = '23514';
    END IF;
    IF NEW.event_timezone IS DISTINCT FROM expected_timezone THEN
        RAISE EXCEPTION 'reservation timezone does not match quotation snapshot'
            USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$function$;

REVOKE ALL ON FUNCTION public.claridez_validate_reservation_coherence() FROM PUBLIC;

CREATE TRIGGER commercial_reservation_coherence
BEFORE INSERT OR UPDATE ON public.commercial_reservation
FOR EACH ROW EXECUTE FUNCTION public.claridez_validate_reservation_coherence();
"""

RESERVATION_COHERENCE_REVERSE = """
DROP TRIGGER IF EXISTS commercial_reservation_coherence ON public.commercial_reservation;
DROP FUNCTION IF EXISTS public.claridez_validate_reservation_coherence();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("commercial", "0002_tenant_security_and_integrity"),
        ("organizations", "0003_membership_organizations_membership_org_id_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "line_subtotal",
                        django.db.models.functions.math.Round(
                            django.db.models.expressions.CombinedExpression(
                                models.F("quantity"), "*", models.F("unit_price")
                            ),
                            precision=2,
                        ),
                    )
                ),
                name="commercial_quoteline_subtotal_product",
            ),
        ),
        migrations.RunSQL(RESERVATION_COHERENCE_FORWARD, RESERVATION_COHERENCE_REVERSE),
    ]
