# Generated by Django 5.2.17 on 2026-09-04 09:06

import django.db.models.deletion
from django.db import migrations, models

FORWARD = """
ALTER TABLE public.commercial_eventrequesthistory
    ADD CONSTRAINT commercial_history_analytics_person_tenant_fk
    FOREIGN KEY (organization_id, analytics_person_id)
    REFERENCES public.commercial_person (organization_id, id);

CREATE FUNCTION public.claridez_capture_request_analytics_identity()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public AS $function$
BEGIN
    IF pg_trigger_depth() < 2 THEN
        RAISE EXCEPTION 'request analytics identity requires source capture'
            USING ERRCODE = '23514';
    END IF;
    SELECT person_id INTO STRICT NEW.analytics_person_id
    FROM public.commercial_eventrequest
    WHERE organization_id = NEW.organization_id AND id = NEW.event_request_id;
    RETURN NEW;
END;
$function$;
REVOKE ALL ON FUNCTION public.claridez_capture_request_analytics_identity() FROM PUBLIC;
CREATE TRIGGER commercial_request_analytics_identity_capture
BEFORE INSERT ON public.commercial_eventrequesthistory
FOR EACH ROW EXECUTE FUNCTION public.claridez_capture_request_analytics_identity();
"""
REVERSE = """
DROP TRIGGER IF EXISTS commercial_request_analytics_identity_capture
    ON public.commercial_eventrequesthistory;
DROP FUNCTION IF EXISTS public.claridez_capture_request_analytics_identity();
ALTER TABLE public.commercial_eventrequesthistory
    DROP CONSTRAINT IF EXISTS commercial_history_analytics_person_tenant_fk;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("commercial", "0008_delete_reservation"),
        ("people", "0005_consentevent_external_evidence_sha256_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrequesthistory",
            name="analytics_person",
            field=models.ForeignKey(
                db_index=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_identity_evidence",
                to="people.person",
            ),
        ),
        migrations.RunSQL(FORWARD, REVERSE),
    ]
