# Generated by Django 5.2.17 on 2026-09-02 05:13

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commercial", "0008_delete_reservation"),
        ("crm", "0003_corrective_integrity"),
        ("organizations", "0004_venues_and_spaces"),
        ("people", "0005_consentevent_external_evidence_sha256_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="communication_purpose",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="interaction",
            name="communication_reference",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interaction",
            name="recorder_kind",
            field=models.CharField(
                choices=[
                    ("internal_membership", "Membresía interna"),
                    ("communications", "Comunicación semántica"),
                ],
                default="internal_membership",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="recorded_by_membership",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_crm_interactions",
                to="organizations.membership",
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="responsible_membership",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsible_crm_interactions",
                to="organizations.membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="interaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("communication_purpose", ""),
                        ("communication_reference__isnull", True),
                        ("recorded_by_membership__isnull", False),
                        ("recorder_kind", "internal_membership"),
                        ("responsible_membership__isnull", False),
                    ),
                    models.Q(
                        (
                            "communication_purpose",
                            django.db.models.functions.text.Trim("communication_purpose"),
                        ),
                        ("communication_reference__isnull", False),
                        ("correction_of__isnull", True),
                        ("recorded_by_membership__isnull", True),
                        ("recorder_kind", "communications"),
                        ("responsible_membership__isnull", True),
                        models.Q(("communication_purpose", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="crm_interaction_recorder_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="interaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recorder_kind", "communications")),
                fields=("organization", "communication_reference"),
                name="crm_interaction_communication_ref_uq",
            ),
        ),
    ]
