# Generated by Django 5.2.16 on 2026-08-15 00:07

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivableObligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("root_reservation_id", models.UUIDField()),
                ("confirmation_source_id", models.UUIDField()),
                ("confirmation_event_id", models.UUIDField()),
                ("event_request_id", models.UUIDField()),
                ("quotation_version_id", models.UUIDField()),
                ("quotation_visible_number", models.CharField(max_length=40)),
                ("quotation_version", models.PositiveIntegerField()),
                ("counterparty_person_id", models.UUIDField()),
                ("counterparty_name_snapshot", models.CharField(max_length=240)),
                ("currency", models.CharField(max_length=3)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=18)),
                ("discount_total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("original_total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("economic_terms_snapshot", models.JSONField(default=dict)),
                ("confirmed_at", models.DateTimeField()),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_receivable_obligations",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceivableAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("increase", "Aumenta la obligación"),
                            ("decrease", "Disminuye la obligación"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("reason", models.CharField(max_length=500)),
                ("correlation_reference", models.CharField(blank=True, max_length=300)),
                ("evidence_reference", models.CharField(blank=True, max_length=300)),
                ("occurred_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_adjustments",
                        to="organizations.membership",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="receivables.receivableobligation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionScheduleRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revision", models.PositiveIntegerField()),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("manual", "Configuración manual"),
                            ("commercial_terms", "Términos comerciales estructurados"),
                            ("legacy_review", "Revisión histórica"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("published_at", models.DateTimeField()),
                (
                    "actor_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_schedule_revisions",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_revisions",
                        to="receivables.receivableobligation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionScheduleDue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_key", models.UUIDField()),
                ("position", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("due_on", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "schedule_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dues",
                        to="receivables.collectionschedulerevision",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_dues",
                        to="receivables.receivableobligation",
                    ),
                ),
            ],
            options={
                "ordering": ["due_on", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReceivedPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("root_reservation_id", models.UUIDField(blank=True, null=True)),
                ("event_request_id", models.UUIDField(blank=True, null=True)),
                ("counterparty_person_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("reported_at", models.DateTimeField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("bank_transfer", "Transferencia bancaria"),
                            ("card_external", "Tarjeta procesada externamente"),
                            ("check", "Cheque"),
                            ("other", "Otro medio externo"),
                            ("legacy_unspecified", "Medio histórico no especificado"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=300)),
                ("normalized_reference", models.CharField(blank=True, max_length=300)),
                ("observation", models.CharField(blank=True, max_length=1000)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("manual", "Registro manual"),
                            ("confirmation_deposit", "Anticipo de confirmación"),
                            ("legacy_5_1_confirmation", "Confirmación histórica 5.1"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "evidence_level",
                    models.CharField(
                        choices=[
                            ("internal_report", "Declaración interna"),
                            ("attached_support", "Comprobante adjunto"),
                        ],
                        max_length=32,
                    ),
                ),
                ("confirmation_source_id", models.UUIDField(blank=True, null=True)),
                ("possible_duplicate", models.BooleanField(default=False)),
                ("duplicate_review_note", models.CharField(blank=True, max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_received_payments",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("year", models.PositiveIntegerField()),
                ("sequence", models.PositiveIntegerField()),
                ("visible_number", models.CharField(max_length=40)),
                ("snapshot", models.JSONField()),
                ("snapshot_sha256", models.CharField(max_length=64)),
                ("issued_at", models.DateTimeField()),
                ("document_artifact_id", models.UUIDField(blank=True, null=True)),
                (
                    "issued_by_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_receivable_receipts",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="receivables.receivableobligation",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="receivables.receivedpayment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_key", models.UUIDField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("applied_at", models.DateTimeField()),
                (
                    "applied_by_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_payment_applications",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_applications",
                        to="receivables.receivableobligation",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="receivables.receivedpayment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("refunded_at", models.DateTimeField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("bank_transfer", "Transferencia bancaria"),
                            ("card_external", "Tarjeta procesada externamente"),
                            ("check", "Cheque"),
                            ("other", "Otro medio externo"),
                            ("legacy_unspecified", "Medio histórico no especificado"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=300)),
                ("reason", models.CharField(max_length=500)),
                ("evidence_reference", models.CharField(blank=True, max_length=300)),
                (
                    "obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="receivables.receivableobligation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="receivables.receivedpayment",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_refunds",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "payment_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_allocations",
                        to="receivables.paymentapplication",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="receivables.refundrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("command_type", models.CharField(max_length=48)),
                ("idempotency_key", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("result_type", models.CharField(max_length=48)),
                ("result_reference", models.UUIDField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="receivables_command_org_id_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "command_type", "idempotency_key"),
                        name="receivables_command_idempotency_uq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=48)),
                ("aggregate_type", models.CharField(max_length=48)),
                ("aggregate_id", models.UUIDField()),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor_membership",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_financial_events",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="receivables_event_org_id_uq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialEvidenceLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner_type", models.CharField(max_length=32)),
                ("owner_id", models.UUIDField()),
                ("document_file_id", models.UUIDField()),
                ("evidence_purpose", models.CharField(max_length=48)),
                (
                    "linked_by_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_financial_evidence_links",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="receivables_evidence_link_org_id_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "owner_type", "owner_id", "document_file_id"),
                        name="receivables_evidence_link_owner_file_uq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LegacyEvidenceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("root_reservation_id", models.UUIDField()),
                ("confirmation_source_id", models.UUIDField()),
                ("classification", models.CharField(max_length=48)),
                ("reason", models.CharField(max_length=500)),
                ("source_snapshot", models.JSONField(default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="receivables_legacy_review_org_id_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "confirmation_source_id"),
                        name="receivables_legacy_review_source_uq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MovementReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("payment", "Pago"),
                            ("application", "Aplicación"),
                            ("adjustment", "Ajuste"),
                            ("refund", "Devolución"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("reason", models.CharField(max_length=500)),
                ("reversed_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "reversed_by_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivable_movement_reversals",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="receivables_reversal_org_id_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "target_kind", "target_id"),
                        name="receivables_reversal_target_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="receivables_reversal_amount_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReceiptSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("next_value", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "year"),
                        name="receivables_receipt_sequence_org_year_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("next_value__gte", 1)),
                        name="receivables_receipt_sequence_positive",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="receivableobligation",
            index=models.Index(
                fields=["organization", "counterparty_person_id", "created_at"],
                name="recv_obligation_person_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receivableobligation",
            index=models.Index(
                fields=["organization", "event_request_id"], name="recv_obligation_request_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivableobligation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="receivables_obligation_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivableobligation",
            constraint=models.UniqueConstraint(
                fields=("organization", "root_reservation_id"),
                name="receivables_obligation_org_root_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="receivableobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quotation_version__gte", 1)),
                name="receivables_obligation_quote_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="receivableobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal__gte", 0),
                    ("discount_total__gte", 0),
                    ("original_total__gte", 0),
                    ("discount_total__lte", models.F("subtotal")),
                    (
                        "original_total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("subtotal"), "-", models.F("discount_total")
                        ),
                    ),
                ),
                name="receivables_obligation_totals_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="receivableadjustment",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="receivables_adjustment_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivableadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="receivables_adjustment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionschedulerevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="receivables_schedule_revision_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionschedulerevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "obligation", "revision"),
                name="receivables_schedule_revision_org_number_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionschedulerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="receivables_schedule_revision_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionscheduledue",
            index=models.Index(
                fields=["organization", "obligation", "due_on"], name="recv_due_obligation_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionscheduledue",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="receivables_due_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionscheduledue",
            constraint=models.UniqueConstraint(
                fields=("organization", "schedule_revision", "position"),
                name="receivables_due_revision_position_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionscheduledue",
            constraint=models.UniqueConstraint(
                fields=("organization", "schedule_revision", "due_key"),
                name="receivables_due_revision_key_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionscheduledue",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="receivables_due_position_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionscheduledue",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="receivables_due_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="receivedpayment",
            index=models.Index(
                fields=["organization", "counterparty_person_id", "reported_at"],
                name="recv_payment_person_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receivedpayment",
            index=models.Index(
                fields=["organization", "root_reservation_id"], name="receivables_payment_root_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivedpayment",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="receivables_payment_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivedpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("confirmation_source_id__isnull", False)),
                fields=("organization", "confirmation_source_id"),
                name="receivables_payment_confirmation_source_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="receivedpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="receivables_payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="receivables_receipt_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                fields=("organization", "year", "sequence"),
                name="receivables_receipt_org_year_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                fields=("organization", "visible_number"), name="receivables_receipt_org_visible_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)), name="receivables_receipt_number_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentapplication",
            index=models.Index(
                fields=["organization", "payment", "created_at"],
                name="recv_application_payment_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentapplication",
            index=models.Index(
                fields=["organization", "obligation", "created_at"], name="recv_app_obligation_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentapplication",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="receivables_application_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="receivables_application_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="refundrecord",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="receivables_refund_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="refundrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="receivables_refund_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="refundapplication",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="receivables_refund_application_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="refundapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="receivables_refund_application_amount_positive",
            ),
        ),
    ]
