# Generated by Django 5.2.16 on 2026-08-01 21:37
# ruff: noqa: E501

import uuid
from datetime import timedelta
from uuid import UUID, uuid5
from zoneinfo import ZoneInfo

import django.db.models.deletion
from django.db import migrations, models

BASELINE_VERSION = "operations-5.2-v1"
BASELINE_NAMESPACE = UUID("6f4bc8cb-3f79-5ed8-a62d-d8d9d688ee53")
BASELINE = (
    ("space_layout", "definitions", "Confirmar distribución del espacio", 7),
    ("guest_count", "definitions", "Revisar número estimado de invitados", 7),
    ("special_requirements", "definitions", "Confirmar requerimientos especiales", 7),
    ("entry_schedule", "definitions", "Validar horario de ingreso", 7),
    ("furniture", "setup", "Preparar mobiliario", 1),
    ("decoration", "setup", "Verificar decoración", 1),
    ("final_readiness_review", "final_review", "Revisar que todo esté listo antes del evento", 0),
)


def _id(reservation_id: object, kind: str, value: str) -> UUID:
    return uuid5(BASELINE_NAMESPACE, f"{reservation_id}:{BASELINE_VERSION}:{kind}:{value}")


def lock_and_preflight(apps, schema_editor):  # type: ignore[no-untyped-def]
    reservation_model = apps.get_model("commercial", "Reservation")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("LOCK TABLE public.commercial_reservation IN SHARE ROW EXCLUSIVE MODE")
        cursor.execute("SELECT clock_timestamp()")
        cutover_at = cursor.fetchone()[0]
        cursor.execute(
            "SELECT set_config('claridez.operations_cutover_at', %s, true)",
            (cutover_at.isoformat(),),
        )
        cursor.execute("SELECT current_setting('claridez.organization_id', true)")
        previous_context = cursor.fetchone()[0] or ""
        cursor.execute("SELECT id FROM public.organizations_organization ORDER BY id")
        organization_ids = [row[0] for row in cursor.fetchall()]
        ambiguous_count = 0
        try:
            for organization_id in organization_ids:
                cursor.execute(
                    "SELECT set_config('claridez.organization_id', %s, true)",
                    (str(organization_id),),
                )
                cursor.execute(
                    """
                    SELECT count(*)
                    FROM public.commercial_reservation AS reservation
                    JOIN public.commercial_quotationversion AS version
                      ON version.organization_id = reservation.organization_id
                     AND version.id = reservation.quotation_version_id
                    LEFT JOIN pg_catalog.pg_timezone_names AS timezone
                      ON timezone.name = reservation.event_timezone
                    WHERE reservation.organization_id = %s AND ((
                        reservation.status = 'confirmed'
                        AND version.event_starts_at_snapshot <= %s
                    ) OR (
                        reservation.status = 'cancelled'
                        AND reservation.confirmed_at IS NOT NULL
                        AND (reservation.cancelled_at IS NULL
                            OR reservation.cancelled_at >= version.event_starts_at_snapshot)
                    ) OR (
                        reservation.confirmed_at IS NOT NULL
                        AND (reservation.confirmed_by_membership_id IS NULL
                            OR version.event_starts_at_snapshot IS NULL
                            OR timezone.name IS NULL)
                    ))
                    """,
                    (organization_id, cutover_at),
                )
                ambiguous_count += cursor.fetchone()[0]
                reservation_model.objects.filter(
                    organization_id=organization_id, confirmed_at__isnull=False
                ).count()
        finally:
            cursor.execute(
                "SELECT set_config('claridez.organization_id', %s, true)",
                (previous_context,),
            )
    if ambiguous_count:
        raise RuntimeError(
            "El preflight de operations encontró reservas históricas no representables: "
            f"{ambiguous_count}. El esquema operativo no fue creado."
        )
    # Fuerza evaluación del modelo histórico bajo el lock antes de crear tablas.


def backfill_operations(apps, schema_editor):  # type: ignore[no-untyped-def]
    reservation_model = apps.get_model("commercial", "Reservation")
    preparation_model = apps.get_model("operations", "EventPreparation")
    item_model = apps.get_model("operations", "PreparationItem")
    transition_model = apps.get_model("operations", "PreparationTransition")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT current_setting('claridez.organization_id', true)")
        previous_context = cursor.fetchone()[0] or ""
        cursor.execute("SELECT id FROM public.organizations_organization ORDER BY id")
        organization_ids = [row[0] for row in cursor.fetchall()]
    reservations = []
    try:
        for organization_id in organization_ids:
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(
                    "SELECT set_config('claridez.organization_id', %s, true)",
                    (str(organization_id),),
                )
            reservations.extend(
                reservation_model.objects.select_related("quotation_version")
                .filter(organization_id=organization_id, confirmed_at__isnull=False)
                .order_by("id")
            )
    finally:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT set_config('claridez.organization_id', %s, true)",
                (previous_context,),
            )
    for reservation in reservations:
        cancelled = reservation.status == "cancelled"
        preparation = preparation_model.objects.create(
            reservation_id=reservation.pk,
            organization_id=reservation.organization_id,
            status="cancelled" if cancelled else "preparing",
            operational_notes="",
            baseline_version=BASELINE_VERSION,
            revision=2 if cancelled else 1,
        )
        event_day = reservation.quotation_version.event_starts_at_snapshot.astimezone(
            ZoneInfo(reservation.event_timezone)
        ).date()
        confirmation_day = reservation.confirmed_at.astimezone(
            ZoneInfo(reservation.event_timezone)
        ).date()
        item_model.objects.bulk_create(
            [
                item_model(
                    id=_id(reservation.pk, "item", key),
                    organization_id=reservation.organization_id,
                    preparation_id=reservation.pk,
                    client_request_id=_id(reservation.pk, "request", key),
                    baseline_key=key,
                    section=section,
                    position=position,
                    title=title,
                    is_required=True,
                    due_on=max(confirmation_day, event_day - timedelta(days=days_before)),
                    status="pending",
                    notes="",
                    status_note="",
                    revision=1,
                )
                for position, (key, section, title, days_before) in enumerate(BASELINE, start=1)
            ]
        )
        transitions = [
            transition_model(
                id=_id(reservation.pk, "transition", "initialized"),
                organization_id=reservation.organization_id,
                preparation_id=reservation.pk,
                from_status=None,
                to_status="preparing",
                cause="initialized",
                actor_membership_id=reservation.confirmed_by_membership_id,
                preparation_revision=1,
                occurred_at=reservation.confirmed_at,
            )
        ]
        if cancelled:
            transitions.append(
                transition_model(
                    id=_id(reservation.pk, "transition", "commercial_cancellation"),
                    organization_id=reservation.organization_id,
                    preparation_id=reservation.pk,
                    from_status="preparing",
                    to_status="cancelled",
                    cause="commercial_cancellation",
                    actor_membership_id=reservation.cancelled_by_membership_id,
                    preparation_revision=2,
                    occurred_at=reservation.cancelled_at,
                )
            )
        transition_model.objects.bulk_create(transitions)
        created_at = reservation.confirmed_at
        updated_at = reservation.cancelled_at if cancelled else reservation.confirmed_at
        preparation_model.objects.filter(pk=preparation.pk).update(
            created_at=created_at, updated_at=updated_at
        )
        item_model.objects.filter(preparation_id=reservation.pk).update(
            created_at=created_at, updated_at=created_at
        )

    with schema_editor.connection.cursor() as cursor:
        try:
            for organization_id in organization_ids:
                cursor.execute(
                    "SELECT set_config('claridez.organization_id', %s, true)",
                    (str(organization_id),),
                )
                cursor.execute(
                    """
                    SELECT count(*)
                    FROM public.commercial_reservation AS reservation
                    LEFT JOIN public.operations_eventpreparation AS preparation
                      ON preparation.organization_id = reservation.organization_id
                     AND preparation.reservation_id = reservation.id
                    WHERE reservation.organization_id = %s AND (
                       (reservation.confirmed_at IS NOT NULL
                           AND preparation.reservation_id IS NULL)
                       OR (reservation.confirmed_at IS NULL
                           AND preparation.reservation_id IS NOT NULL)
                       OR (reservation.status = 'cancelled'
                           AND reservation.confirmed_at IS NOT NULL
                           AND preparation.status <> 'cancelled'))
                    """,
                    (organization_id,),
                )
                if cursor.fetchone()[0]:
                    raise RuntimeError(
                        "El backfill operativo no satisface la cardinalidad requerida."
                    )
        finally:
            cursor.execute(
                "SELECT set_config('claridez.organization_id', %s, true)",
                (previous_context,),
            )
        cursor.execute(
            """
            SELECT count(*)
            FROM public.operations_eventpreparation AS preparation
            WHERE (SELECT count(*) FROM public.operations_preparationitem AS item
                   WHERE item.organization_id = preparation.organization_id
                     AND item.preparation_id = preparation.reservation_id
                     AND item.baseline_key IS NOT NULL) <> 7
               OR (SELECT count(*) FROM public.operations_preparationitem AS item
                   WHERE item.organization_id = preparation.organization_id
                     AND item.preparation_id = preparation.reservation_id
                     AND item.baseline_key IN (
                       'space_layout', 'guest_count', 'special_requirements', 'entry_schedule',
                       'furniture', 'decoration', 'final_readiness_review')) <> 7
            """
        )
        if cursor.fetchone()[0]:
            raise RuntimeError("El backfill operativo no creó las siete claves base.")


TENANT_AND_INTEGRITY_FORWARD = r"""
ALTER TABLE public.commercial_reservation NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.operations_eventpreparation
    ADD CONSTRAINT operations_prep_tenant_reservation_fk
    FOREIGN KEY (organization_id, reservation_id)
    REFERENCES public.commercial_reservation (organization_id, id);
ALTER TABLE public.commercial_reservation FORCE ROW LEVEL SECURITY;
ALTER TABLE public.operations_eventpreparation
    ADD CONSTRAINT operations_prep_tenant_responsible_fk
    FOREIGN KEY (organization_id, responsible_membership_id)
    REFERENCES public.organizations_membership (organization_id, id);
ALTER TABLE public.operations_eventpreparation
    ADD CONSTRAINT operations_prep_tenant_ready_by_fk
    FOREIGN KEY (organization_id, ready_by_membership_id)
    REFERENCES public.organizations_membership (organization_id, id);
ALTER TABLE public.operations_eventpreparation
    ADD CONSTRAINT operations_prep_tenant_started_by_fk
    FOREIGN KEY (organization_id, started_by_membership_id)
    REFERENCES public.organizations_membership (organization_id, id);
ALTER TABLE public.operations_eventpreparation
    ADD CONSTRAINT operations_prep_tenant_completed_by_fk
    FOREIGN KEY (organization_id, completed_by_membership_id)
    REFERENCES public.organizations_membership (organization_id, id);

ALTER TABLE public.operations_preparationitem
    ADD CONSTRAINT operations_item_tenant_preparation_fk
    FOREIGN KEY (organization_id, preparation_id)
    REFERENCES public.operations_eventpreparation (organization_id, reservation_id);
ALTER TABLE public.operations_preparationitem
    ADD CONSTRAINT operations_item_tenant_responsible_fk
    FOREIGN KEY (organization_id, responsible_membership_id)
    REFERENCES public.organizations_membership (organization_id, id);
ALTER TABLE public.operations_preparationitem
    ADD CONSTRAINT operations_item_tenant_resolved_by_fk
    FOREIGN KEY (organization_id, resolved_by_membership_id)
    REFERENCES public.organizations_membership (organization_id, id);

ALTER TABLE public.operations_preparationtransition
    ADD CONSTRAINT operations_transition_tenant_preparation_fk
    FOREIGN KEY (organization_id, preparation_id)
    REFERENCES public.operations_eventpreparation (organization_id, reservation_id);
ALTER TABLE public.operations_preparationtransition
    ADD CONSTRAINT operations_transition_tenant_actor_fk
    FOREIGN KEY (organization_id, actor_membership_id)
    REFERENCES public.organizations_membership (organization_id, id);

CREATE FUNCTION public.claridez_guard_event_preparation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
DECLARE
    reservation_status text;
    baseline_count integer;
    expected_baseline_count integer;
    item_count integer;
    distinct_position_count integer;
    minimum_position integer;
    maximum_position integer;
    unresolved_count integer;
    blocked_count integer;
    final_status text;
    responsible_count integer;
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status NOT IN ('preparing', 'cancelled') THEN
            RAISE EXCEPTION 'invalid initial preparation status' USING ERRCODE = '23514';
        END IF;
    ELSE
        IF OLD.status IN ('completed', 'cancelled')
           AND (to_jsonb(NEW) - 'updated_at') IS DISTINCT FROM (to_jsonb(OLD) - 'updated_at') THEN
            RAISE EXCEPTION 'terminal preparations are immutable' USING ERRCODE = '23514';
        END IF;
        IF NEW.status <> OLD.status AND NOT (
            (OLD.status = 'preparing' AND NEW.status IN ('ready', 'cancelled'))
            OR (OLD.status = 'ready' AND NEW.status IN ('preparing', 'in_progress', 'cancelled'))
            OR (OLD.status = 'in_progress' AND NEW.status = 'completed')
        ) THEN
            RAISE EXCEPTION 'invalid preparation transition' USING ERRCODE = '23514';
        END IF;
    END IF;
    SELECT status INTO reservation_status
    FROM public.commercial_reservation
    WHERE organization_id = NEW.organization_id AND id = NEW.reservation_id;
    IF NEW.status IN ('preparing', 'ready', 'in_progress', 'completed')
       AND reservation_status IS DISTINCT FROM 'confirmed' THEN
        RAISE EXCEPTION 'active preparation requires confirmed reservation' USING ERRCODE = '23514';
    END IF;
    IF NEW.status = 'cancelled' AND reservation_status IS DISTINCT FROM 'cancelled' THEN
        RAISE EXCEPTION 'cancelled preparation requires cancelled reservation' USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND ((OLD.status = 'in_progress' AND NEW.status = 'cancelled')
       OR (OLD.status = 'completed' AND NEW.status = 'cancelled')) THEN
        RAISE EXCEPTION 'executed preparation cannot be cancelled' USING ERRCODE = '23514';
    END IF;
    IF NEW.status = 'preparing' AND (NEW.ready_at IS NOT NULL
       OR NEW.started_at IS NOT NULL OR NEW.completed_at IS NOT NULL) THEN
        RAISE EXCEPTION 'preparing evidence is inconsistent' USING ERRCODE = '23514';
    ELSIF NEW.status = 'ready' AND (NEW.ready_at IS NULL
       OR NEW.started_at IS NOT NULL OR NEW.completed_at IS NOT NULL) THEN
        RAISE EXCEPTION 'ready evidence is inconsistent' USING ERRCODE = '23514';
    ELSIF NEW.status = 'in_progress' AND (NEW.ready_at IS NULL
       OR NEW.started_at IS NULL OR NEW.completed_at IS NOT NULL) THEN
        RAISE EXCEPTION 'execution evidence is inconsistent' USING ERRCODE = '23514';
    ELSIF NEW.status = 'completed' AND (NEW.ready_at IS NULL
       OR NEW.started_at IS NULL OR NEW.completed_at IS NULL) THEN
        RAISE EXCEPTION 'completion evidence is inconsistent' USING ERRCODE = '23514';
    ELSIF NEW.status = 'cancelled' AND (NEW.started_at IS NOT NULL
       OR NEW.completed_at IS NOT NULL) THEN
        RAISE EXCEPTION 'cancellation evidence is inconsistent' USING ERRCODE = '23514';
    END IF;
    IF (NEW.ready_at IS NOT NULL AND NEW.started_at IS NOT NULL
       AND NEW.ready_at > NEW.started_at)
       OR (NEW.started_at IS NOT NULL AND NEW.completed_at IS NOT NULL
       AND NEW.started_at > NEW.completed_at) THEN
        RAISE EXCEPTION 'preparation evidence chronology is inconsistent' USING ERRCODE = '23514';
    END IF;
    IF NEW.status = 'ready' AND (TG_OP = 'INSERT' OR OLD.status <> 'ready') THEN
        IF NEW.responsible_membership_id IS NULL THEN
            RAISE EXCEPTION 'ready preparation requires responsible' USING ERRCODE = '23514';
        END IF;
        SELECT count(*) INTO responsible_count
        FROM public.organizations_membership
        WHERE organization_id = NEW.organization_id
          AND id = NEW.responsible_membership_id
          AND status = 'active' AND role IN ('owner', 'administrator', 'operations');
        IF responsible_count <> 1 THEN
            RAISE EXCEPTION 'ready preparation requires eligible responsible'
                USING ERRCODE = '23514';
        END IF;
        SELECT
            count(*) FILTER (WHERE baseline_key IS NOT NULL),
            count(*) FILTER (WHERE baseline_key IN (
                'space_layout', 'guest_count', 'special_requirements', 'entry_schedule',
                'furniture', 'decoration', 'final_readiness_review'
            )),
            count(*), count(DISTINCT position), min(position), max(position),
            count(*) FILTER (WHERE is_required AND status NOT IN ('completed', 'not_applicable')),
            count(*) FILTER (WHERE status = 'blocked'),
            max(status) FILTER (WHERE baseline_key = 'final_readiness_review')
        INTO baseline_count, expected_baseline_count, item_count, distinct_position_count,
            minimum_position, maximum_position, unresolved_count, blocked_count, final_status
        FROM public.operations_preparationitem
        WHERE organization_id = NEW.organization_id AND preparation_id = NEW.reservation_id;
        IF baseline_count <> 7 OR expected_baseline_count <> 7
           OR item_count <> distinct_position_count OR minimum_position <> 1
           OR maximum_position <> item_count
           OR unresolved_count <> 0 OR blocked_count <> 0
           OR final_status IS DISTINCT FROM 'completed' THEN
            RAISE EXCEPTION 'preparation is not ready' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION public.claridez_guard_event_preparation() FROM PUBLIC;
CREATE TRIGGER operations_preparation_guard
BEFORE INSERT OR UPDATE ON public.operations_eventpreparation
FOR EACH ROW EXECUTE FUNCTION public.claridez_guard_event_preparation();

CREATE FUNCTION public.claridez_guard_preparation_item()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
DECLARE parent_status text; resolver_count integer;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'preparation items cannot be deleted' USING ERRCODE = '23514';
    END IF;
    SELECT status INTO parent_status
    FROM public.operations_eventpreparation
    WHERE organization_id = NEW.organization_id AND reservation_id = NEW.preparation_id;
    IF parent_status IN ('in_progress', 'completed', 'cancelled') THEN
        RAISE EXCEPTION 'preparation items are frozen' USING ERRCODE = '23514';
    END IF;
    IF parent_status = 'ready' AND (
        NEW.status = 'blocked'
        OR (NEW.is_required AND NEW.status NOT IN ('completed', 'not_applicable'))
        OR (TG_OP = 'UPDATE' AND OLD.status IN ('completed', 'not_applicable')
            AND ROW(NEW.title, NEW.notes, NEW.section, NEW.is_required)
                IS DISTINCT FROM ROW(OLD.title, OLD.notes, OLD.section, OLD.is_required))
    ) THEN
        RAISE EXCEPTION 'invalidating ready checklist requires atomic reopening'
            USING ERRCODE = '23514';
    END IF;
    IF TG_OP = 'UPDATE' AND ROW(NEW.organization_id, NEW.preparation_id, NEW.client_request_id,
       NEW.baseline_key) IS DISTINCT FROM ROW(OLD.organization_id, OLD.preparation_id,
       OLD.client_request_id, OLD.baseline_key) THEN
        RAISE EXCEPTION 'preparation item identity is immutable' USING ERRCODE = '23514';
    END IF;
    IF NEW.baseline_key IS NOT NULL AND NOT NEW.is_required THEN
        RAISE EXCEPTION 'baseline items are required' USING ERRCODE = '23514';
    END IF;
    IF NEW.status IN ('completed', 'not_applicable')
       AND (TG_OP = 'INSERT' OR OLD.status IS DISTINCT FROM NEW.status
            OR OLD.resolved_at IS DISTINCT FROM NEW.resolved_at
            OR OLD.resolved_by_membership_id IS DISTINCT FROM NEW.resolved_by_membership_id) THEN
        SELECT count(*) INTO resolver_count
        FROM public.organizations_membership
        WHERE organization_id = NEW.organization_id
          AND id = NEW.resolved_by_membership_id
          AND status = 'active' AND role IN ('owner', 'administrator', 'operations');
        IF resolver_count <> 1 THEN
            RAISE EXCEPTION 'item resolution requires eligible actor' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION public.claridez_guard_preparation_item() FROM PUBLIC;
CREATE TRIGGER operations_item_guard
BEFORE INSERT OR UPDATE OR DELETE ON public.operations_preparationitem
FOR EACH ROW EXECUTE FUNCTION public.claridez_guard_preparation_item();

CREATE FUNCTION public.claridez_guard_preparation_transition()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $function$
DECLARE current_status text; current_revision integer;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'preparation transitions are append-only' USING ERRCODE = '23514';
    END IF;
    SELECT status, revision INTO current_status, current_revision
    FROM public.operations_eventpreparation
    WHERE organization_id = NEW.organization_id AND reservation_id = NEW.preparation_id;
    IF current_status IS DISTINCT FROM NEW.to_status
       OR current_revision IS DISTINCT FROM NEW.preparation_revision THEN
        RAISE EXCEPTION 'transition does not match preparation' USING ERRCODE = '23514';
    END IF;
    IF NOT (
        (NEW.cause = 'initialized' AND NEW.from_status IS NULL
            AND NEW.to_status = 'preparing' AND NEW.preparation_revision = 1)
        OR (NEW.cause = 'readiness_declared' AND NEW.from_status = 'preparing'
            AND NEW.to_status = 'ready')
        OR (NEW.cause = 'checklist_reopened' AND NEW.from_status = 'ready'
            AND NEW.to_status = 'preparing')
        OR (NEW.cause = 'execution_started' AND NEW.from_status = 'ready'
            AND NEW.to_status = 'in_progress')
        OR (NEW.cause = 'execution_completed' AND NEW.from_status = 'in_progress'
            AND NEW.to_status = 'completed')
        OR (NEW.cause = 'commercial_cancellation'
            AND NEW.from_status IN ('preparing', 'ready') AND NEW.to_status = 'cancelled')
    ) THEN
        RAISE EXCEPTION 'invalid preparation transition cause' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION public.claridez_guard_preparation_transition() FROM PUBLIC;
CREATE TRIGGER operations_transition_guard
BEFORE INSERT OR UPDATE OR DELETE ON public.operations_preparationtransition
FOR EACH ROW EXECUTE FUNCTION public.claridez_guard_preparation_transition();

REVOKE ALL ON TABLE public.operations_eventpreparation,
    public.operations_preparationitem, public.operations_preparationtransition FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON TABLE public.operations_eventpreparation,
    public.operations_preparationitem, public.operations_preparationtransition TO claridez_app;
ALTER TABLE public.operations_eventpreparation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operations_eventpreparation FORCE ROW LEVEL SECURITY;
ALTER TABLE public.operations_preparationitem ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operations_preparationitem FORCE ROW LEVEL SECURITY;
ALTER TABLE public.operations_preparationtransition ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operations_preparationtransition FORCE ROW LEVEL SECURITY;
CREATE POLICY operations_preparation_tenant_policy
ON public.operations_eventpreparation AS PERMISSIVE FOR ALL
TO claridez_app, claridez_migrator, claridez_test_runner
USING (organization_id = public.claridez_current_organization_id())
WITH CHECK (organization_id = public.claridez_current_organization_id());
CREATE POLICY operations_item_tenant_policy
ON public.operations_preparationitem AS PERMISSIVE FOR ALL
TO claridez_app, claridez_migrator, claridez_test_runner
USING (organization_id = public.claridez_current_organization_id())
WITH CHECK (organization_id = public.claridez_current_organization_id());
CREATE POLICY operations_transition_tenant_policy
ON public.operations_preparationtransition AS PERMISSIVE FOR ALL
TO claridez_app, claridez_migrator, claridez_test_runner
USING (organization_id = public.claridez_current_organization_id())
WITH CHECK (organization_id = public.claridez_current_organization_id());
"""

TENANT_AND_INTEGRITY_REVERSE = r"""
DROP POLICY IF EXISTS operations_transition_tenant_policy ON public.operations_preparationtransition;
DROP POLICY IF EXISTS operations_item_tenant_policy ON public.operations_preparationitem;
DROP POLICY IF EXISTS operations_preparation_tenant_policy ON public.operations_eventpreparation;
ALTER TABLE public.operations_preparationtransition NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.operations_preparationtransition DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.operations_preparationitem NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.operations_preparationitem DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.operations_eventpreparation NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.operations_eventpreparation DISABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS operations_transition_guard ON public.operations_preparationtransition;
DROP FUNCTION IF EXISTS public.claridez_guard_preparation_transition();
DROP TRIGGER IF EXISTS operations_item_guard ON public.operations_preparationitem;
DROP FUNCTION IF EXISTS public.claridez_guard_preparation_item();
DROP TRIGGER IF EXISTS operations_preparation_guard ON public.operations_eventpreparation;
DROP FUNCTION IF EXISTS public.claridez_guard_event_preparation();
ALTER TABLE public.operations_preparationtransition DROP CONSTRAINT IF EXISTS operations_transition_tenant_actor_fk;
ALTER TABLE public.operations_preparationtransition DROP CONSTRAINT IF EXISTS operations_transition_tenant_preparation_fk;
ALTER TABLE public.operations_preparationitem DROP CONSTRAINT IF EXISTS operations_item_tenant_resolved_by_fk;
ALTER TABLE public.operations_preparationitem DROP CONSTRAINT IF EXISTS operations_item_tenant_responsible_fk;
ALTER TABLE public.operations_preparationitem DROP CONSTRAINT IF EXISTS operations_item_tenant_preparation_fk;
ALTER TABLE public.operations_eventpreparation DROP CONSTRAINT IF EXISTS operations_prep_tenant_completed_by_fk;
ALTER TABLE public.operations_eventpreparation DROP CONSTRAINT IF EXISTS operations_prep_tenant_started_by_fk;
ALTER TABLE public.operations_eventpreparation DROP CONSTRAINT IF EXISTS operations_prep_tenant_ready_by_fk;
ALTER TABLE public.operations_eventpreparation DROP CONSTRAINT IF EXISTS operations_prep_tenant_responsible_fk;
ALTER TABLE public.operations_eventpreparation DROP CONSTRAINT IF EXISTS operations_prep_tenant_reservation_fk;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("commercial", "0003_hardening_5_1_1"),
        ("organizations", "0003_membership_organizations_membership_org_id_unique"),
    ]

    operations = [
        migrations.RunPython(lock_and_preflight, migrations.RunPython.noop),
        migrations.CreateModel(
            name="EventPreparation",
            fields=[
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="preparation",
                        serialize=False,
                        to="commercial.reservation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "En preparación"),
                            ("ready", "Listo"),
                            ("in_progress", "En ejecución"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="preparing",
                        max_length=16,
                    ),
                ),
                ("operational_notes", models.TextField(blank=True, max_length=4000)),
                (
                    "baseline_version",
                    models.CharField(default="operations-5.2-v1", editable=False, max_length=32),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_event_preparations",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "ready_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readied_event_preparations",
                        to="organizations.membership",
                    ),
                ),
                (
                    "responsible_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_event_preparations",
                        to="organizations.membership",
                    ),
                ),
                (
                    "started_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="started_event_preparations",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreparationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_request_id", models.UUIDField()),
                ("baseline_key", models.CharField(blank=True, max_length=48, null=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("definitions", "Definiciones"),
                            ("setup", "Preparación"),
                            ("final_review", "Revisión final"),
                        ],
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=160)),
                ("is_required", models.BooleanField(default=True)),
                ("due_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_progress", "En curso"),
                            ("blocked", "Bloqueado"),
                            ("completed", "Completado"),
                            ("not_applicable", "No aplica"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=2000)),
                ("status_note", models.CharField(blank=True, max_length=500)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="operations.eventpreparation",
                    ),
                ),
                (
                    "resolved_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_preparation_items",
                        to="organizations.membership",
                    ),
                ),
                (
                    "responsible_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_preparation_items",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PreparationTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("preparing", "En preparación"),
                            ("ready", "Listo"),
                            ("in_progress", "En ejecución"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("initialized", "Inicializada"),
                            ("readiness_declared", "Lista"),
                            ("checklist_reopened", "Checklist reabierto"),
                            ("execution_started", "Ejecución iniciada"),
                            ("execution_completed", "Ejecución completada"),
                            ("commercial_cancellation", "Cancelación comercial"),
                        ],
                        max_length=32,
                    ),
                ),
                ("preparation_revision", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.membership"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions",
                        to="operations.eventpreparation",
                    ),
                ),
            ],
            options={
                "ordering": ["preparation_revision", "occurred_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="eventpreparation",
            index=models.Index(
                fields=["organization", "status"], name="operations_prep_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventpreparation",
            index=models.Index(
                fields=["organization", "responsible_membership"], name="operations_prep_owner_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventpreparation",
            constraint=models.UniqueConstraint(
                fields=("organization", "reservation"), name="operations_preparation_org_res_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventpreparation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["preparing", "ready", "in_progress", "completed", "cancelled"])
                ),
                name="operations_preparation_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventpreparation",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="operations_preparation_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventpreparation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ready_at__isnull", True), ("ready_by_membership__isnull", True)),
                    models.Q(("ready_at__isnull", False), ("ready_by_membership__isnull", False)),
                    _connector="OR",
                ),
                name="operations_preparation_ready_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventpreparation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("started_at__isnull", True), ("started_by_membership__isnull", True)),
                    models.Q(
                        ("started_at__isnull", False), ("started_by_membership__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="operations_preparation_started_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventpreparation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True), ("completed_by_membership__isnull", True)
                    ),
                    models.Q(
                        ("completed_at__isnull", False), ("completed_by_membership__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="operations_preparation_completed_evidence",
            ),
        ),
        migrations.AddIndex(
            model_name="preparationitem",
            index=models.Index(
                fields=["organization", "preparation", "status"], name="operations_item_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preparationitem",
            index=models.Index(fields=["organization", "due_on"], name="operations_item_due_idx"),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_item_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "preparation", "position"),
                name="operations_item_org_position_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "preparation", "client_request_id"),
                name="operations_item_org_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("baseline_key__isnull", False)),
                fields=("organization", "preparation", "baseline_key"),
                name="operations_item_org_baseline_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("section__in", ["definitions", "setup", "final_review"])),
                name="operations_item_section_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["pending", "in_progress", "blocked", "completed", "not_applicable"],
                    )
                ),
                name="operations_item_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1), ("revision__gte", 1)),
                name="operations_item_numbers_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("resolved_at__isnull", False),
                        ("resolved_by_membership__isnull", False),
                        ("status__in", ["completed", "not_applicable"]),
                    ),
                    models.Q(
                        ("resolved_at__isnull", True),
                        ("resolved_by_membership__isnull", True),
                        ("status__in", ["pending", "in_progress", "blocked"]),
                    ),
                    _connector="OR",
                ),
                name="operations_item_resolution_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["blocked", "not_applicable"]),
                        models.Q(("status_note", ""), _negated=True),
                    ),
                    models.Q(
                        ("status__in", ["pending", "in_progress", "completed"]), ("status_note", "")
                    ),
                    _connector="OR",
                ),
                name="operations_item_status_note_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("baseline_key", "final_readiness_review"),
                    ("status", "not_applicable"),
                    _negated=True,
                ),
                name="operations_final_review_applies",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationtransition",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_transition_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationtransition",
            constraint=models.UniqueConstraint(
                fields=("organization", "preparation", "preparation_revision"),
                name="operations_transition_org_revision_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationtransition",
            constraint=models.CheckConstraint(
                condition=models.Q(("preparation_revision__gte", 1)),
                name="operations_transition_revision_positive",
            ),
        ),
        migrations.RunPython(backfill_operations, migrations.RunPython.noop),
        migrations.RunSQL(TENANT_AND_INTEGRITY_FORWARD, TENANT_AND_INTEGRITY_REVERSE),
    ]
