# Generated by Django 5.2.17 on 2026-08-25 06:41

import uuid
from typing import Any

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


def classify_existing_preparation_items(apps: Any, schema_editor: Any) -> None:
    del apps
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id FROM organizations_organization ORDER BY id")
        organization_ids = [row[0] for row in cursor.fetchall()]
        cursor.execute("SELECT current_setting('claridez.organization_id', true)")
        previous_context = cursor.fetchone()[0] or ""
        # This is a one-time provenance classification, not an operational edit.
        # The 5.2 trigger correctly freezes terminal preparation items, so the
        # migrator suspends only that trigger inside this atomic migration.
        cursor.execute(
            "ALTER TABLE operations_preparationitem DISABLE TRIGGER operations_item_guard"
        )
        for organization_id in organization_ids:
            cursor.execute(
                "SELECT set_config('claridez.organization_id', %s, true)",
                [str(organization_id)],
            )
            cursor.execute(
                "UPDATE operations_preparationitem "
                "SET source_kind = 'baseline_5_2' "
                "WHERE organization_id = %s AND baseline_key IS NOT NULL",
                [organization_id],
            )
            cursor.execute(
                "UPDATE operations_preparationitem SET source_kind = 'manual' "
                "WHERE organization_id = %s AND baseline_key IS NULL",
                [organization_id],
            )
        cursor.execute(
            "ALTER TABLE operations_preparationitem ENABLE TRIGGER operations_item_guard"
        )
        cursor.execute(
            "SELECT set_config('claridez.organization_id', %s, true)",
            [previous_context],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_catalog_history_integrity"),
        ("documents", "0010_domain_asset_security"),
        ("operations", "0004_remove_eventpreparation_operations_preparation_status_valid_and_more"),
        ("organizations", "0004_venues_and_spaces"),
        ("resources", "0002_temporal_asset_availability_hardening"),
        ("scheduling", "0009_allow_terminal_operational_successors"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateResourceNeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=64)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "start_anchor",
                    models.CharField(
                        choices=[
                            ("occupied_start", "Inicio de ocupación"),
                            ("event_start", "Inicio del evento"),
                            ("event_end", "Fin del evento"),
                            ("occupied_end", "Fin de ocupación"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_offset_minutes", models.IntegerField(default=0)),
                (
                    "end_anchor",
                    models.CharField(
                        choices=[
                            ("occupied_start", "Inicio de ocupación"),
                            ("event_start", "Inicio del evento"),
                            ("event_end", "Fin del evento"),
                            ("occupied_end", "Fin de ocupación"),
                        ],
                        max_length=20,
                    ),
                ),
                ("end_offset_minutes", models.IntegerField(default=0)),
                ("position", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TemplateRoleDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=120)),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("setup", "Montaje"),
                            ("execution", "Ejecución"),
                            ("teardown", "Desmontaje"),
                            ("post_event", "Postevento"),
                        ],
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="preparationitem",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("baseline_5_2", "Baseline 5.2"),
                    ("manual", "Manual"),
                    ("p13_template_readiness", "Readiness de plantilla P13"),
                ],
                default="manual",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="preparationitem",
            name="template_role_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(classify_existing_preparation_items, migrations.RunPython.noop),
        migrations.CreateModel(
            name="OperationalChangeProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("readiness", "Readiness"),
                            ("verification", "Verificación"),
                            ("responsibility", "Responsabilidad"),
                            ("resource_need", "Necesidad de recurso"),
                            ("resource_window", "Ventana de recurso"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("before_payload", models.JSONField(default=dict)),
                ("proposed_payload", models.JSONField(default=dict)),
                ("reason", models.CharField(max_length=1000)),
                ("expected_preparation_revision", models.PositiveIntegerField()),
                ("idempotency_key", models.UUIDField()),
                ("payload_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="change_proposals",
                        to="operations.eventpreparation",
                    ),
                ),
                (
                    "proposed_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposed_operational_changes",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalChangeDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField()),
                ("reason", models.CharField(max_length=1000)),
                ("expected_preparation_revision", models.PositiveIntegerField()),
                ("idempotency_key", models.UUIDField()),
                ("payload_sha256", models.CharField(max_length=64)),
                ("decided_at", models.DateTimeField()),
                (
                    "decided_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_operational_changes",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="operations.operationalchangeproposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("verification", "Verificación"),
                            ("incident", "Incidencia"),
                            ("change", "Cambio"),
                            ("close", "Cierre"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("idempotency_key", models.UUIDField()),
                (
                    "document_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_evidence_links",
                        to="documents.privatedomainfile",
                    ),
                ),
                (
                    "linked_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linked_operational_evidence",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_evidence",
                        to="operations.eventpreparation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("safety", "Seguridad"),
                            ("schedule_or_space", "Agenda o espacio"),
                            ("resource", "Recurso"),
                            ("supplier", "Proveedor"),
                            ("service_quality", "Calidad del servicio"),
                            ("customer_scope", "Alcance del cliente"),
                            ("other_operational", "Otra operativa"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierta"),
                            ("contained", "Contenida"),
                            ("resolved", "Resuelta"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
                ("impact", models.CharField(max_length=1000)),
                ("reported_at", models.DateTimeField()),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="operations.eventpreparation",
                    ),
                ),
                (
                    "reported_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_operational_incidents",
                        to="organizations.membership",
                    ),
                ),
                (
                    "responsible_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_operational_incidents",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalIncidentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opened", "Abierta"),
                            ("contained", "Contenida"),
                            ("resolved", "Resuelta"),
                            ("reassigned", "Reasignada"),
                            ("impact_updated", "Impacto actualizado"),
                            ("corrected", "Corregida"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=12)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("open", "Abierta"),
                            ("contained", "Contenida"),
                            ("resolved", "Resuelta"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        max_length=12,
                    ),
                ),
                ("impact", models.CharField(max_length=1000)),
                ("detail", models.CharField(blank=True, max_length=1000)),
                ("incident_revision", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("idempotency_key", models.UUIDField()),
                (
                    "actor_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_incident_events",
                        to="organizations.membership",
                    ),
                ),
                (
                    "corrects",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="operations.operationalincidentevent",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="operations.operationalincident",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "responsible_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_incident_events_as_responsible",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["incident_revision", "occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="OperationalPhaseFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "phase",
                    models.CharField(
                        choices=[("setup", "Montaje"), ("teardown", "Desmontaje")], max_length=12
                    ),
                ),
                (
                    "fact_kind",
                    models.CharField(
                        choices=[("started", "Iniciada"), ("completed", "Finalizada")],
                        max_length=12,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("preparation_revision", models.PositiveIntegerField()),
                ("idempotency_key", models.UUIDField()),
                ("provenance", models.CharField(default="user_observation", max_length=32)),
                ("correction_reason", models.CharField(blank=True, max_length=500)),
                ("payload_sha256", models.CharField(max_length=64)),
                (
                    "actor_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_phase_facts",
                        to="organizations.membership",
                    ),
                ),
                (
                    "corrects",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction",
                        to="operations.operationalphasefact",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase_facts",
                        to="operations.eventpreparation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="OperationalPlanSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("organization", "Organizacional"),
                            ("system", "Sistema"),
                            ("legacy_cutover", "Cutover legado"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_version", models.CharField(max_length=80)),
                ("event_type_id", models.UUIDField()),
                ("event_type_label", models.CharField(max_length=100)),
                ("canonical_payload", models.JSONField(default=dict)),
                ("content_sha256", models.CharField(max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_snapshot",
                        to="operations.eventpreparation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalResourceWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("root_reservation_id", models.UUIDField()),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=20)),
                ("required_interval", django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ("window_revision", models.PositiveIntegerField(default=1)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("organization_template", "Plantilla organizacional"),
                            ("system_template", "Plantilla de sistema"),
                            ("authorized_change", "Cambio autorizado"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source_version", models.CharField(max_length=80)),
                ("schedule_reservation_revision", models.PositiveIntegerField()),
                ("schedule_source_revision", models.PositiveIntegerField()),
                ("idempotency_key", models.UUIDField()),
                ("payload_sha256", models.CharField(max_length=64)),
                (
                    "authorization_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_windows",
                        to="operations.operationalchangedecision",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="operations.operationalresourcewindow",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_windows",
                        to="operations.eventpreparation",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_resource_windows",
                        to="scheduling.reservation",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_windows",
                        to="resources.resource",
                    ),
                ),
                (
                    "schedule_allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_resource_windows",
                        to="scheduling.scheduleallocation",
                    ),
                ),
                (
                    "schedule_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_resource_windows",
                        to="scheduling.scheduleevent",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_windows",
                        to="operations.operationalplansnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalResponsibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role_key", models.CharField(max_length=64)),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("setup", "Montaje"),
                            ("execution", "Ejecución"),
                            ("teardown", "Desmontaje"),
                            ("post_event", "Postevento"),
                        ],
                        max_length=16,
                    ),
                ),
                ("preparation_revision", models.PositiveIntegerField()),
                ("idempotency_key", models.UUIDField()),
                (
                    "assigned_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_operational_responsibilities",
                        to="organizations.membership",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_responsibilities",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsibilities",
                        to="operations.eventpreparation",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsibilities",
                        to="operations.operationalplansnapshot",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="operations.operationalresponsibility",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_operational_templates",
                        to="organizations.membership",
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_templates",
                        to="catalog.eventtype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicada"),
                            ("retired", "Retirada"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_operational_template_versions",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "published_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_operational_template_versions",
                        to="organizations.membership",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="operations.operationaltemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="operationalplansnapshot",
            name="template_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_snapshots",
                to="operations.operationaltemplateversion",
            ),
        ),
        migrations.CreateModel(
            name="OperationalVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_key", models.CharField(max_length=64)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("setup", "Montaje"),
                            ("execution", "Ejecución"),
                            ("teardown", "Desmontaje"),
                            ("post_event", "Postevento"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("is_required", models.BooleanField(default=True)),
                ("role_key", models.CharField(blank=True, max_length=64)),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("completed", "Completada"),
                            ("not_applicable", "No aplica"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("status_reason", models.CharField(blank=True, max_length=500)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_operational_verifications",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase_verifications",
                        to="operations.eventpreparation",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifications",
                        to="operations.operationalplansnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["phase", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="OperationalVerificationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_status", models.CharField(max_length=16)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("completed", "Completada"),
                            ("not_applicable", "No aplica"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("verification_revision", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("idempotency_key", models.UUIDField()),
                (
                    "actor_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_verification_events",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="operations.operationalverification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("command_type", models.CharField(max_length=48)),
                ("idempotency_key", models.UUIDField()),
                ("payload_sha256", models.CharField(max_length=64)),
                ("result_kind", models.CharField(max_length=48)),
                ("result_id", models.UUIDField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostEventClose",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField()),
                ("preparation_revision", models.PositiveIntegerField()),
                ("source_snapshot", models.JSONField(default=dict)),
                ("source_sha256", models.CharField(max_length=64)),
                ("idempotency_key", models.UUIDField()),
                (
                    "closed_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_operational_events",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "preparation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_event_close",
                        to="operations.eventpreparation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostEventCloseCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=1000)),
                ("correction_payload", models.JSONField(default=dict)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("idempotency_key", models.UUIDField()),
                (
                    "close",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="operations.posteventclose",
                    ),
                ),
                (
                    "corrected_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrected_operational_closes",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadinessDeviation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("before_payload", models.JSONField(default=dict)),
                ("effective_payload", models.JSONField(default=dict)),
                ("reason", models.CharField(max_length=1000)),
                ("item_revision", models.PositiveIntegerField()),
                ("payload_sha256", models.CharField(max_length=64)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readiness_deviation",
                        to="operations.operationalchangedecision",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readiness_deviations",
                        to="operations.preparationitem",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplatePhaseDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=64)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("setup", "Montaje"),
                            ("execution", "Ejecución"),
                            ("teardown", "Desmontaje"),
                            ("post_event", "Postevento"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("is_required", models.BooleanField(default=True)),
                ("role_key", models.CharField(blank=True, max_length=64)),
                ("position", models.PositiveIntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="phase_definitions",
                        to="operations.operationaltemplateversion",
                    ),
                ),
            ],
            options={
                "ordering": ["phase", "position", "id"],
            },
        ),
        migrations.AddField(
            model_name="operationalverification",
            name="definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_verifications",
                to="operations.templatephasedefinition",
            ),
        ),
        migrations.CreateModel(
            name="TemplateReadinessDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=160)),
                ("section", models.CharField(max_length=16)),
                ("is_required", models.BooleanField(default=True)),
                ("days_before", models.PositiveIntegerField(default=0)),
                ("role_key", models.CharField(blank=True, max_length=64)),
                ("position", models.PositiveIntegerField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readiness_definitions",
                        to="operations.operationaltemplateversion",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="preparationitem",
            name="template_readiness_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preparation_items",
                to="operations.templatereadinessdefinition",
            ),
        ),
        migrations.AddConstraint(
            model_name="preparationitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("baseline_key__isnull", False),
                        ("source_kind", "baseline_5_2"),
                        ("template_readiness_definition__isnull", True),
                    ),
                    models.Q(
                        ("baseline_key__isnull", True),
                        ("source_kind", "manual"),
                        ("template_readiness_definition__isnull", True),
                    ),
                    models.Q(
                        ("baseline_key__isnull", True),
                        ("source_kind", "p13_template_readiness"),
                        ("template_readiness_definition__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="operations_item_source_shape_valid",
            ),
        ),
        migrations.AddField(
            model_name="templateresourceneed",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="templateresourceneed",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operational_template_needs",
                to="resources.resource",
            ),
        ),
        migrations.AddField(
            model_name="templateresourceneed",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resource_needs",
                to="operations.operationaltemplateversion",
            ),
        ),
        migrations.AddField(
            model_name="operationalresourcewindow",
            name="resource_need",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_windows",
                to="operations.templateresourceneed",
            ),
        ),
        migrations.AddField(
            model_name="templateroledefinition",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="templateroledefinition",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_definitions",
                to="operations.operationaltemplateversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalchangeproposal",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_change_proposal_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalchangeproposal",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="operations_change_proposal_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalchangedecision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_change_decision_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalchangedecision",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="operations_change_decision_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalevidence",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_evidence_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalevidence",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="operations_evidence_request_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalevidence",
            constraint=models.UniqueConstraint(
                fields=("organization", "preparation", "target_kind", "target_id", "document_file"),
                name="operations_evidence_target_file_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalincident",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_incident_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalincident",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="operations_incident_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalincidentevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_incident_event_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalincidentevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "incident", "incident_revision"),
                name="operations_incident_event_revision_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalincidentevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="operations_incident_event_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalincidentevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("corrects__isnull", False), ("kind", "corrected")),
                    models.Q(("kind", "corrected"), _negated=True),
                    _connector="OR",
                ),
                name="operations_incident_event_correction_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalphasefact",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_phase_fact_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalphasefact",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="operations_phase_fact_request_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalphasefact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("corrects__isnull", True)),
                fields=("organization", "preparation", "phase", "fact_kind"),
                name="operations_phase_fact_original_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalphasefact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("correction_reason", ""), ("corrects__isnull", True)),
                    models.Q(
                        ("corrects__isnull", False),
                        models.Q(("correction_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="operations_phase_fact_correction_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalresponsibility",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_responsibility_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalresponsibility",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="operations_responsibility_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaltemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_template_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaltemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "event_type"), name="operations_template_event_type_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaltemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="operations_template_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaltemplateversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_template_version_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaltemplateversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "template", "version"),
                name="operations_template_version_number_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaltemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="operations_template_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationaltemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("published_at__isnull", True),
                        ("published_by_membership__isnull", True),
                        ("retired_at__isnull", True),
                        ("status", "draft"),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("published_by_membership__isnull", False),
                        ("retired_at__isnull", True),
                        ("status", "published"),
                    ),
                    models.Q(
                        ("published_at__isnull", False),
                        ("published_by_membership__isnull", False),
                        ("retired_at__isnull", False),
                        ("status", "retired"),
                    ),
                    _connector="OR",
                ),
                name="operations_template_version_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalplansnapshot",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_plan_snapshot_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalplansnapshot",
            constraint=models.UniqueConstraint(
                fields=("organization", "preparation"), name="operations_plan_snapshot_prep_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalplansnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_kind", "organization"), ("template_version__isnull", False)),
                    models.Q(
                        ("source_kind__in", ["system", "legacy_cutover"]),
                        ("template_version__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="operations_plan_snapshot_source_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalverificationevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_verification_event_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalverificationevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "verification", "verification_revision"),
                name="operations_verification_event_revision_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalverificationevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="operations_verification_event_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationcommand",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_command_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationcommand",
            constraint=models.UniqueConstraint(
                fields=("organization", "command_type", "idempotency_key"),
                name="operations_command_idempotency_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="posteventclose",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_post_close_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="posteventclose",
            constraint=models.UniqueConstraint(
                fields=("organization", "preparation"), name="operations_post_close_prep_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="posteventclose",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"), name="operations_post_close_request_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="posteventclosecorrection",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_post_close_correction_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="posteventclosecorrection",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="operations_post_close_correction_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="readinessdeviation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_readiness_deviation_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="templatephasedefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_phase_definition_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="templatephasedefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "version", "key"), name="operations_phase_definition_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="templatephasedefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "version", "phase", "position"),
                name="operations_phase_definition_position_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatephasedefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="operations_phase_definition_position_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalverification",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_verification_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalverification",
            constraint=models.UniqueConstraint(
                fields=("organization", "preparation", "source_key"),
                name="operations_verification_source_key_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalverification",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1), ("revision__gte", 1)),
                name="operations_verification_numbers_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalverification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("completed_by_membership__isnull", True),
                        ("status", "pending"),
                        ("status_reason", ""),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("completed_by_membership__isnull", False),
                        ("status", "completed"),
                        ("status_reason", ""),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("completed_by_membership__isnull", False),
                        ("status", "not_applicable"),
                        models.Q(("status_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="operations_verification_resolution_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatereadinessdefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_readiness_definition_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="templatereadinessdefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "version", "key"),
                name="operations_readiness_definition_key_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatereadinessdefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "version", "position"),
                name="operations_readiness_definition_position_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatereadinessdefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="operations_readiness_definition_position_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="templateresourceneed",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_resource_need_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="templateresourceneed",
            constraint=models.UniqueConstraint(
                fields=("organization", "version", "key"), name="operations_resource_need_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="templateresourceneed",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="operations_resource_need_quantity_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="templateresourceneed",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="operations_resource_need_position_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalresourcewindow",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_resource_window_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalresourcewindow",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="operations_resource_window_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalresourcewindow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__gt", 0),
                    ("window_revision__gte", 1),
                    ("schedule_reservation_revision__gte", 1),
                    ("schedule_source_revision__gte", 1),
                ),
                name="operations_resource_window_numbers_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalresourcewindow",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("authorization_decision__isnull", False),
                        ("source_kind", "authorized_change"),
                    ),
                    models.Q(
                        ("source_kind__in", ["organization_template", "system_template"]),
                        ("authorization_decision__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="operations_resource_window_source_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="templateroledefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="operations_role_definition_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="templateroledefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "version", "key"), name="operations_role_definition_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="templateroledefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)),
                name="operations_role_definition_position_ck",
            ),
        ),
    ]
