# Generated by Django 5.2.17 on 2026-08-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0008_refresh_p13_guardians"),
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationalverificationevent",
            name="correction_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="operationalverificationevent",
            name="corrects",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction",
                to="operations.operationalverificationevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalverificationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("correction_reason", ""), ("corrects__isnull", True)),
                    models.Q(
                        ("corrects__isnull", False),
                        models.Q(("correction_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="operations_verification_event_correction_ck",
            ),
        ),
    ]
