# Generated by Django 5.2.17 on 2026-08-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0009_operationalverificationevent_correction_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationalincidentevent",
            name="corrects",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correction",
                to="operations.operationalincidentevent",
            ),
        ),
    ]
