# Generated by Django 5.2.17 on 2026-09-04 08:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

SQL = r"""
ALTER TABLE operations_preparationanalyticsstate ENABLE ROW LEVEL SECURITY;
ALTER TABLE operations_preparationanalyticsstate FORCE ROW LEVEL SECURITY;
CREATE POLICY operations_p15_state_tenant ON operations_preparationanalyticsstate
USING (organization_id = NULLIF(current_setting('claridez.organization_id', true), '')::uuid)
WITH CHECK (organization_id = NULLIF(current_setting('claridez.organization_id', true), '')::uuid);
REVOKE ALL ON operations_preparationanalyticsstate FROM PUBLIC, claridez_app;
GRANT SELECT, INSERT ON operations_preparationanalyticsstate TO claridez_app;
ALTER TABLE operations_preparationanalyticsstate ADD CONSTRAINT operations_p15_state_prep_fk
FOREIGN KEY (organization_id, preparation_id)
REFERENCES operations_eventpreparation(organization_id, reservation_id)
DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE operations_preparationanalyticsstate ADD CONSTRAINT operations_p15_state_member_fk
FOREIGN KEY (organization_id, responsible_membership_id)
REFERENCES organizations_membership(organization_id, id) DEFERRABLE INITIALLY DEFERRED;

CREATE FUNCTION operations_guard_p15_state() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP <> 'INSERT' OR pg_trigger_depth() < 2 THEN
        RAISE EXCEPTION 'source preparation state is append only and source captured'
            USING ERRCODE = '23514';
    END IF;
    NEW.recorded_at := clock_timestamp();
    RETURN NEW;
END; $$;
CREATE TRIGGER operations_p15_state_guard BEFORE INSERT OR UPDATE OR DELETE
ON operations_preparationanalyticsstate FOR EACH ROW EXECUTE FUNCTION operations_guard_p15_state();
CREATE TRIGGER operations_p15_state_truncate BEFORE TRUNCATE ON operations_preparationanalyticsstate
FOR EACH STATEMENT EXECUTE FUNCTION operations_guard_p15_state();

CREATE FUNCTION operations_capture_p15_state() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' OR ROW(NEW.status, NEW.responsible_membership_id)
        IS DISTINCT FROM ROW(OLD.status, OLD.responsible_membership_id) THEN
        INSERT INTO operations_preparationanalyticsstate
            (id, organization_id, preparation_id, preparation_revision, status,
             responsible_membership_id, recorded_at)
        VALUES (gen_random_uuid(), NEW.organization_id, NEW.reservation_id, NEW.revision,
            NEW.status, NEW.responsible_membership_id, clock_timestamp());
    END IF;
    RETURN NEW;
END; $$;
CREATE TRIGGER operations_capture_p15_state AFTER INSERT OR UPDATE
ON operations_eventpreparation FOR EACH ROW EXECUTE FUNCTION operations_capture_p15_state();
"""

REVERSE = r"""
DROP TRIGGER operations_capture_p15_state ON operations_eventpreparation;
DROP FUNCTION operations_capture_p15_state();
DROP TRIGGER operations_p15_state_guard ON operations_preparationanalyticsstate;
DROP TRIGGER operations_p15_state_truncate ON operations_preparationanalyticsstate;
DROP FUNCTION operations_guard_p15_state();
ALTER TABLE operations_preparationanalyticsstate DROP CONSTRAINT operations_p15_state_prep_fk;
ALTER TABLE operations_preparationanalyticsstate DROP CONSTRAINT operations_p15_state_member_fk;
DROP POLICY operations_p15_state_tenant ON operations_preparationanalyticsstate;
ALTER TABLE operations_preparationanalyticsstate NO FORCE ROW LEVEL SECURITY;
ALTER TABLE operations_preparationanalyticsstate DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON operations_preparationanalyticsstate FROM claridez_app;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0019_preparation_transition_recorded_at"),
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreparationAnalyticsState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("preparation_revision", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "En preparación"),
                            ("ready", "Listo"),
                            ("in_progress", "En ejecución"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                            ("rescheduled", "Reprogramado"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.eventpreparation",
                    ),
                ),
                (
                    "responsible_membership",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "preparation", "recorded_at"],
                        name="operations_p15_state_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="operations_p15_state_org_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "preparation", "preparation_revision"),
                        name="operations_p15_state_rev_uq",
                    ),
                ],
            },
        ),
        migrations.RunSQL(SQL, reverse_sql=REVERSE),
    ]
