# Generated by Django 5.2.16 on 2026-07-31 23:39

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(db_index=False, max_length=63)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activa"), ("suspended", "Suspendida")], max_length=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("name", ""), _negated=True),
                            ("name", django.db.models.functions.text.Trim("name")),
                        ),
                        name="organizations_organization_name_canonical",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("slug__regex", "^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?$"),
                            models.Q(("slug__contains", "--"), _negated=True),
                        ),
                        name="organizations_organization_slug_canonical",
                    ),
                    models.UniqueConstraint(
                        fields=("slug",), name="organizations_organization_slug_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "suspended"])),
                        name="organizations_organization_status_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Propietario"),
                            ("administrator", "Administrador"),
                            ("commercial", "Comercial"),
                            ("operations", "Operaciones"),
                            ("finance", "Finanzas"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("suspended", "Suspendida"),
                            ("revoked", "Revocada"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("role", "owner"), ("status", "active")),
                        fields=["organization"],
                        name="organizations_active_owner_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"),
                        name="organizations_membership_org_user_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "role__in",
                                ["owner", "administrator", "commercial", "operations", "finance"],
                            )
                        ),
                        name="organizations_membership_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "suspended", "revoked"])),
                        name="organizations_membership_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("revoked_at__isnull", True),
                                ("status", "active"),
                                ("suspended_at__isnull", True),
                            ),
                            models.Q(
                                ("revoked_at__isnull", True),
                                ("status", "suspended"),
                                ("suspended_at__isnull", False),
                            ),
                            models.Q(("revoked_at__isnull", False), ("status", "revoked")),
                            _connector="OR",
                        ),
                        name="organizations_membership_status_dates_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("suspended_at__isnull", True),
                            ("suspended_at__gte", models.F("joined_at")),
                            _connector="OR",
                        ),
                        name="organizations_membership_suspended_after_joined",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revoked_at__isnull", True),
                            ("revoked_at__gte", models.F("joined_at")),
                            _connector="OR",
                        ),
                        name="organizations_membership_revoked_after_joined",
                    ),
                ],
            },
        ),
    ]
