# Generated by Django 5.2.16 on 2026-08-01 00:55

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import claridez.organizations.normalization


def create_existing_organization_settings(apps, schema_editor):  # type: ignore[no-untyped-def]
    organization_model = apps.get_model("organizations", "Organization")
    settings_model = apps.get_model("organizations", "OrganizationSettings")
    settings_model.objects.bulk_create(
        [
            settings_model(
                organization_id=organization_id,
                currency="USD",
                timezone="America/Guayaquil",
            )
            for organization_id in organization_model.objects.values_list("pk", flat=True)
        ]
    )


TIMEZONE_FUNCTION_FORWARD_SQL = """
CREATE FUNCTION public.claridez_is_iana_timezone(value pg_catalog.text)
RETURNS boolean
LANGUAGE sql
STABLE
PARALLEL SAFE
SET search_path = pg_catalog
AS $function$
    SELECT $1 IS NOT NULL AND EXISTS (
        SELECT 1
        FROM pg_catalog.pg_timezone_names
        WHERE name = $1
    )
$function$;

REVOKE ALL ON FUNCTION public.claridez_is_iana_timezone(pg_catalog.text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claridez_is_iana_timezone(pg_catalog.text)
    TO claridez_app, claridez_migrator, claridez_test_runner;
"""

TIMEZONE_FUNCTION_REVERSE_SQL = """
DROP FUNCTION IF EXISTS public.claridez_is_iana_timezone(pg_catalog.text);
"""


RLS_FORWARD_SQL = """
CREATE FUNCTION public.claridez_current_organization_id()
RETURNS pg_catalog.uuid
LANGUAGE sql
STABLE
PARALLEL SAFE
SET search_path = pg_catalog
AS $function$
    SELECT NULLIF(
        pg_catalog.current_setting('claridez.organization_id', true),
        ''
    )::pg_catalog.uuid
$function$;

REVOKE ALL ON FUNCTION public.claridez_current_organization_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.claridez_current_organization_id()
    TO claridez_app, claridez_migrator, claridez_test_runner;

REVOKE ALL ON TABLE public.organizations_organizationsettings FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON TABLE public.organizations_organizationsettings TO claridez_app;

ALTER TABLE public.organizations_organizationsettings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations_organizationsettings FORCE ROW LEVEL SECURITY;

CREATE POLICY organizations_settings_tenant_policy
ON public.organizations_organizationsettings
AS PERMISSIVE
FOR ALL
TO claridez_app, claridez_migrator, claridez_test_runner
USING (organization_id = public.claridez_current_organization_id())
WITH CHECK (organization_id = public.claridez_current_organization_id());
"""

RLS_REVERSE_SQL = """
DROP POLICY IF EXISTS organizations_settings_tenant_policy
    ON public.organizations_organizationsettings;
ALTER TABLE public.organizations_organizationsettings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.organizations_organizationsettings DISABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.organizations_organizationsettings FROM claridez_app;
DROP FUNCTION IF EXISTS public.claridez_current_organization_id();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            TIMEZONE_FUNCTION_FORWARD_SQL,
            TIMEZONE_FUNCTION_REVERSE_SQL,
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="settings",
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "timezone",
                    models.CharField(
                        default="America/Guayaquil",
                        max_length=64,
                        validators=[claridez.organizations.normalization.validate_iana_timezone],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "organization settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                        name="organizations_settings_currency_canonical",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("timezone", ""), _negated=True),
                            ("timezone", django.db.models.functions.text.Trim("timezone")),
                        ),
                        name="organizations_settings_timezone_canonical",
                    ),
                    models.CheckConstraint(
                        condition=claridez.organizations.normalization.PostgreSQLTimezoneIsValid(
                            models.F("timezone")
                        ),
                        name="organizations_settings_timezone_iana_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            create_existing_organization_settings,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(RLS_FORWARD_SQL, RLS_REVERSE_SQL),
    ]
