# Generated by Django 5.2.17 on 2026-09-01 03:23

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_venues_and_spaces"),
        ("people", "0004_contact_ownership_locking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consentevent",
            name="external_evidence_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="consentevent",
            name="external_submission_reference",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="consentevent",
            name="observed_text_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="consentevent",
            name="presentation_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="consentevent",
            name="recorder_kind",
            field=models.CharField(
                choices=[
                    ("internal_membership", "Membresía interna"),
                    ("external_subject", "Titular externo"),
                ],
                default="internal_membership",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="personrevision",
            name="actor_kind",
            field=models.CharField(
                choices=[
                    ("internal_user", "Usuario interno"),
                    ("external_subject", "Titular externo"),
                ],
                default="internal_user",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="personrevision",
            name="external_evidence_reference",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="personrevision",
            name="external_evidence_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="consentevent",
            name="recorded_by_membership",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recorded_consents",
                to="organizations.membership",
            ),
        ),
        migrations.AlterField(
            model_name="personrevision",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="consentevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("external_evidence_sha256", ""),
                        ("external_submission_reference", ""),
                        ("observed_text_sha256", ""),
                        ("presentation_version", ""),
                        ("recorded_by_membership__isnull", False),
                        ("recorder_kind", "internal_membership"),
                    ),
                    models.Q(
                        ("external_evidence_sha256__regex", "^[0-9a-f]{64}$"),
                        (
                            "external_submission_reference",
                            django.db.models.functions.text.Trim("external_submission_reference"),
                        ),
                        ("observed_text_sha256__regex", "^[0-9a-f]{64}$"),
                        (
                            "presentation_version",
                            django.db.models.functions.text.Trim("presentation_version"),
                        ),
                        ("recorded_by_membership__isnull", True),
                        ("recorder_kind", "external_subject"),
                        models.Q(("external_submission_reference", ""), _negated=True),
                        models.Q(("presentation_version", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="people_consentevent_recorder_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="personrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actor_kind", "internal_user"),
                        ("changed_by__isnull", False),
                        ("external_evidence_reference", ""),
                        ("external_evidence_sha256", ""),
                    ),
                    models.Q(
                        ("actor_kind", "external_subject"),
                        ("changed_by__isnull", True),
                        (
                            "external_evidence_reference",
                            django.db.models.functions.text.Trim("external_evidence_reference"),
                        ),
                        ("external_evidence_sha256__regex", "^[0-9a-f]{64}$"),
                        models.Q(("external_evidence_reference", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="commercial_personrevision_actor_valid",
            ),
        ),
    ]
