# Generated by Django 5.2.17 on 2026-09-01 03:23
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntiAbuseTokenUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_hmac", models.CharField(max_length=64, unique=True)),
                ("action", models.CharField(max_length=32)),
                ("hostname", models.CharField(max_length=240)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PortalAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=48)),
                ("principal_reference", models.UUIDField(blank=True, null=True)),
                ("grant_reference", models.UUIDField(blank=True, null=True)),
                ("actor_membership_id", models.UUIDField(blank=True, null=True)),
                ("result", models.CharField(max_length=24)),
                ("detail", models.JSONField(default=dict)),
                ("request_fingerprint", models.CharField(blank=True, max_length=64)),
                ("occurred_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PortalPrincipal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("person_reference", models.UUIDField()),
                ("canonical_set", models.JSONField(default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("collision", "Colisión pendiente"),
                            ("disabled", "Deshabilitado"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortalGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("person_reference", models.UUIDField()),
                ("event_request_reference", models.UUIDField()),
                ("root_reservation_reference", models.UUIDField(blank=True, null=True)),
                ("scopes", models.JSONField(default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("revoked", "Revocado"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("issued_by_membership_id", models.UUIDField(blank=True, null=True)),
                ("provenance", models.CharField(max_length=32)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_by_membership_id", models.UUIDField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="portal.portalprincipal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortalChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("authentication", "Autenticación"),
                            ("enrollment", "Enrolamiento"),
                            ("recovery", "Recuperación"),
                        ],
                        max_length=16,
                    ),
                ),
                ("channel", models.CharField(max_length=16)),
                ("contact_fingerprint", models.CharField(max_length=64)),
                ("contact_revision", models.PositiveIntegerField()),
                ("code_hmac", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challenges",
                        to="portal.portalprincipal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortalRateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key_hmac", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=32)),
                ("window_started_at", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key_hmac", "action", "window_started_at"),
                        name="portal_rate_bucket_uq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PortalSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("token_hmac", models.CharField(max_length=64, unique=True)),
                ("contact_fingerprint", models.CharField(max_length=64)),
                ("contact_revision", models.PositiveIntegerField()),
                ("idle_expires_at", models.DateTimeField()),
                ("absolute_expires_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("rotation", models.PositiveIntegerField(default=1)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=80)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="portal.portalprincipal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activa"), ("retired", "Retirada")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("created_by_membership_id", models.UUIDField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicFormVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicada"),
                            ("retired", "Retirada"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("introduction", models.CharField(blank=True, max_length=500)),
                ("field_schema", models.JSONField(default=dict)),
                ("event_type_options", models.JSONField(default=list)),
                ("location_options", models.JSONField(default=list)),
                ("duration_options_minutes", models.JSONField(default=list)),
                ("timezone_name", models.CharField(max_length=64)),
                ("responsible_membership_id", models.UUIDField()),
                ("origin", models.CharField(max_length=24)),
                ("origin_detail", models.CharField(blank=True, max_length=160)),
                ("attribution", models.JSONField(default=dict)),
                ("consent_presentation", models.JSONField(default=list)),
                ("portal_scopes", models.JSONField(default=list)),
                ("acknowledgement_template_version_id", models.UUIDField(blank=True, null=True)),
                ("configuration_sha256", models.CharField(max_length=64)),
                ("created_by_membership_id", models.UUIDField()),
                ("published_by_membership_id", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="portal.publicform",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicFormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key_hmac", models.CharField(max_length=64)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("evidence_sha256", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("processing", "Procesando"),
                            ("completed", "Completada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="processing",
                        max_length=12,
                    ),
                ),
                ("person_reference", models.UUIDField(blank=True, null=True)),
                ("event_request_reference", models.UUIDField(blank=True, null=True)),
                ("consent_event_references", models.JSONField(default=list)),
                ("availability_observed", models.BooleanField(blank=True, null=True)),
                ("attribution_sha256", models.CharField(max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "form_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="portal.publicformversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortalLocator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hmac", models.CharField(max_length=64, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("public_form", "Formulario publicado"),
                            ("challenge", "Challenge"),
                            ("recovery", "Recuperación"),
                            ("session", "Sesión Portal"),
                            ("communications_webhook", "Webhook de comunicaciones"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_reference", models.UUIDField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.organization"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["token_hmac", "kind"], name="portal_locator_lookup_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="portalprincipal",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="portal_principal_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalprincipal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("organization", "person_reference"),
                name="portal_principal_active_person_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="portalprincipal",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="portal_principal_revision_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalgrant",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="portal_grant_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("organization", "principal", "event_request_reference"),
                name="portal_grant_active_request_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="portalgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="portal_grant_revision_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("issued_by_membership_id__isnull", True),
                        ("provenance", "public_capture"),
                    ),
                    models.Q(
                        ("issued_by_membership_id__isnull", False),
                        ("provenance", "internal_issue"),
                    ),
                    _connector="OR",
                ),
                name="portal_grant_provenance_actor_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="portalgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("revoked_at__isnull", True),
                        ("revoked_by_membership_id__isnull", True),
                        ("state", "active"),
                    ),
                    models.Q(
                        ("revoked_at__isnull", False),
                        ("revoked_by_membership_id__isnull", False),
                        ("state", "revoked"),
                    ),
                    _connector="OR",
                ),
                name="portal_grant_state_evidence_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="portalchallenge",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="portal_challenge_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_count__lte", models.F("max_attempts"))),
                name="portal_challenge_attempt_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="portalchallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("consumed_at__isnull", False),
                    ("revoked_at__isnull", False),
                    _negated=True,
                ),
                name="portal_challenge_one_terminal_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="portalsession",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="portal_session_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("rotation__gte", 1)), name="portal_session_rotation_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_seen_at__lte", models.F("idle_expires_at")),
                    ("idle_expires_at__lte", models.F("absolute_expires_at")),
                ),
                name="portal_session_expiry_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicform",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="portal_publicform_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicform",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="portal_publicform_name_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicformversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="portal_formversion_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicformversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "form", "version"), name="portal_formversion_number_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicformversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("organization", "form"),
                name="portal_formversion_one_published_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicformversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="portal_formversion_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicformsubmission",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="portal_submission_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicformsubmission",
            constraint=models.UniqueConstraint(
                fields=("organization", "form_version", "idempotency_key_hmac"),
                name="portal_submission_idempotency_uq",
            ),
        ),
    ]
