# Generated by Django 5.2.16 on 2026-07-31 21:43

import uuid

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models

import claridez.identity.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates that this user has all permissions without explicitly "
                            "assigning them."
                        ),
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pendiente de verificación"),
                            ("active", "Activo"),
                            ("suspended", "Suspendido"),
                        ],
                        default="pending_verification",
                        max_length=20,
                    ),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "security_version",
                    models.BigIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The groups this user belongs to. A user will get all permissions "
                            "granted to each of their groups."
                        ),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("email", ""), _negated=True),
                            (
                                "email",
                                django.db.models.functions.text.Lower(
                                    django.db.models.functions.text.Trim("email")
                                ),
                            ),
                        ),
                        name="identity_user_email_canonical",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_active", True), ("status", "active")),
                            models.Q(
                                ("is_active", False),
                                ("status__in", ["pending_verification", "suspended"]),
                            ),
                            _connector="OR",
                        ),
                        name="identity_user_status_active_consistent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("security_version__gte", 1)),
                        name="identity_user_security_version_positive",
                    ),
                ],
            },
            managers=[
                ("objects", claridez.identity.managers.UserManager()),
            ],
        ),
    ]
