# Generated by Django 5.2.17 on 2026-09-04 09:16

import django.db.models.deletion
from django.db import migrations, models

FORWARD = """
ALTER TABLE public.scheduling_scheduleevent
    ADD CONSTRAINT scheduling_p15_previous_venue_tenant_fk
    FOREIGN KEY (organization_id, analytics_previous_venue_id)
    REFERENCES public.organizations_venue (organization_id, id);
ALTER TABLE public.scheduling_scheduleevent
    ADD CONSTRAINT scheduling_p15_new_venue_tenant_fk
    FOREIGN KEY (organization_id, analytics_new_venue_id)
    REFERENCES public.organizations_venue (organization_id, id);
CREATE FUNCTION public.claridez_capture_schedule_analytics_venues()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public AS $function$
BEGIN
    -- Captura al registrar el evento; no se rellenan eventos históricos existentes.
    NEW.analytics_previous_venue_id := NULL;
    NEW.analytics_new_venue_id := NULL;
    IF NEW.previous_snapshot ? 'space_id' THEN
        SELECT venue_id INTO NEW.analytics_previous_venue_id FROM public.organizations_space
        WHERE organization_id = NEW.organization_id
            AND id = (NEW.previous_snapshot ->> 'space_id')::uuid;
    END IF;
    IF NEW.new_snapshot ? 'space_id' THEN
        SELECT venue_id INTO NEW.analytics_new_venue_id FROM public.organizations_space
        WHERE organization_id = NEW.organization_id
            AND id = (NEW.new_snapshot ->> 'space_id')::uuid;
    END IF;
    RETURN NEW;
END;
$function$;
REVOKE ALL ON FUNCTION public.claridez_capture_schedule_analytics_venues() FROM PUBLIC;
CREATE TRIGGER scheduling_analytics_venues_capture
BEFORE INSERT ON public.scheduling_scheduleevent
FOR EACH ROW EXECUTE FUNCTION public.claridez_capture_schedule_analytics_venues();
"""
REVERSE = """
DROP TRIGGER IF EXISTS scheduling_analytics_venues_capture ON public.scheduling_scheduleevent;
DROP FUNCTION IF EXISTS public.claridez_capture_schedule_analytics_venues();
ALTER TABLE public.scheduling_scheduleevent
    DROP CONSTRAINT IF EXISTS scheduling_p15_previous_venue_tenant_fk;
ALTER TABLE public.scheduling_scheduleevent
    DROP CONSTRAINT IF EXISTS scheduling_p15_new_venue_tenant_fk;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_venues_and_spaces"),
        ("scheduling", "0009_allow_terminal_operational_successors"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleevent",
            name="analytics_new_venue",
            field=models.ForeignKey(
                db_index=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="new_schedule_analytics_evidence",
                to="organizations.venue",
            ),
        ),
        migrations.AddField(
            model_name="scheduleevent",
            name="analytics_previous_venue",
            field=models.ForeignKey(
                db_index=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="previous_schedule_analytics_evidence",
                to="organizations.venue",
            ),
        ),
        migrations.RunSQL(FORWARD, REVERSE),
    ]
