# Generated by Django 5.2.17 on 2026-08-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0005_templateresourceneed_templateroledefinition_and_more"),
        ("organizations", "0004_venues_and_spaces"),
        ("resources", "0002_temporal_asset_availability_hardening"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcerequirement",
            name="operational_window",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resource_requirements",
                to="operations.operationalresourcewindow",
            ),
        ),
        migrations.AddField(
            model_name="resourcerequirement",
            name="temporal_source",
            field=models.CharField(
                choices=[
                    ("scheduling_event_interval", "Intervalo del evento"),
                    ("operations_window", "Ventana operacional"),
                ],
                default="scheduling_event_interval",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcerequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("operational_window__isnull", False)),
                fields=("organization", "operational_window"),
                name="resources_requirement_operation_window_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcerequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("operational_window__isnull", True),
                        ("temporal_source", "scheduling_event_interval"),
                    ),
                    models.Q(
                        ("operational_window__isnull", False),
                        ("temporal_source", "operations_window"),
                    ),
                    _connector="OR",
                ),
                name="resources_requirement_temporal_source_ck",
            ),
        ),
    ]
