# Generated by Django 5.2.17 on 2026-09-01 03:23
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=48)),
                ("aggregate_type", models.CharField(max_length=48)),
                ("aggregate_id", models.UUIDField()),
                ("actor_membership_id", models.UUIDField(blank=True, null=True)),
                ("detail", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("portal_authentication", "Autenticación Portal"),
                            ("capture_acknowledgement", "Acuse de captación"),
                            ("service_update", "Actualización de servicio"),
                            ("event_reminder", "Recordatorio de evento"),
                            ("payment_reminder", "Recordatorio de cobro"),
                            ("document_reminder", "Recordatorio documental"),
                            ("client_action", "Acción del cliente"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Correo"), ("whatsapp", "WhatsApp")], max_length=16
                    ),
                ),
                ("recipient_person_id", models.UUIDField()),
                ("aggregate_type", models.CharField(max_length=48)),
                ("aggregate_id", models.UUIDField()),
                ("variables", models.JSONField(default=dict)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=160)),
                ("source_version", models.PositiveIntegerField(default=1)),
                ("causal_key", models.CharField(blank=True, max_length=160)),
                ("causal_sequence", models.PositiveBigIntegerField(blank=True, null=True)),
                ("not_before", models.DateTimeField()),
                ("requested_by_membership_id", models.UUIDField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("materialized", "Materializada"),
                            ("cancelled", "Cancelada"),
                            ("superseded", "Obsoleta"),
                            ("terminal", "Terminal"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("claimed", "Reclamada"),
                            ("retry", "Reintento"),
                            ("succeeded", "Completada"),
                            ("dead", "Fallo terminal"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("next_attempt_at", models.DateTimeField()),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_by", models.CharField(blank=True, max_length=120)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=8)),
                ("last_error_category", models.CharField(blank=True, max_length=48)),
                ("last_error_detail", models.CharField(blank=True, max_length=500)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_entry",
                        to="communications.communicationintent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Correo"), ("whatsapp", "WhatsApp")], max_length=16
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("portal_authentication", "Autenticación Portal"),
                            ("capture_acknowledgement", "Acuse de captación"),
                            ("service_update", "Actualización de servicio"),
                            ("event_reminder", "Recordatorio de evento"),
                            ("payment_reminder", "Recordatorio de cobro"),
                            ("document_reminder", "Recordatorio documental"),
                            ("client_action", "Acción del cliente"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_by_membership_id", models.UUIDField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicada"),
                            ("retired", "Retirada"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("subject_template", models.CharField(blank=True, max_length=240)),
                ("body_template", models.TextField()),
                ("variable_names", models.JSONField(default=list)),
                ("content_sha256", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_by_membership_id", models.UUIDField(blank=True, null=True)),
                ("first_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="communications.communicationtemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="communicationintent",
            name="template_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intents",
                to="communications.communicationtemplateversion",
            ),
        ),
        migrations.CreateModel(
            name="LogicalMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Correo"), ("whatsapp", "WhatsApp")], max_length=16
                    ),
                ),
                ("recipient_fingerprint", models.CharField(max_length=64)),
                ("resolved_variables", models.JSONField(default=dict)),
                ("template_sha256", models.CharField(max_length=64)),
                ("final_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("provider_accepted", "Aceptada por proveedor"),
                            ("delivered", "Entregada"),
                            ("bounced", "Rebotada"),
                            ("failed", "Fallida"),
                            ("suppressed", "Suprimida"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=32)),
                ("provider_message_id", models.CharField(blank=True, max_length=240)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message",
                        to="communications.communicationintent",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="communications.communicationtemplateversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempt", models.PositiveSmallIntegerField()),
                ("provider", models.CharField(max_length=32)),
                ("provider_idempotency_key", models.CharField(max_length=200)),
                ("provider_message_id", models.CharField(blank=True, max_length=240)),
                ("outcome", models.CharField(max_length=24)),
                ("error_category", models.CharField(blank=True, max_length=48)),
                ("response_code", models.CharField(blank=True, max_length=32)),
                ("retry_after_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "outbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="communications.communicationoutbox",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="communications.logicalmessage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="communicationoutbox",
            name="message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outbox_entry",
                to="communications.logicalmessage",
            ),
        ),
        migrations.CreateModel(
            name="ProviderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("provider", models.CharField(max_length=32)),
                ("provider_account", models.CharField(max_length=120)),
                ("provider_event_id", models.CharField(max_length=240)),
                ("event_type", models.CharField(max_length=80)),
                ("external_message_id", models.CharField(blank=True, max_length=240)),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                ("signature_timestamp", models.DateTimeField()),
                ("payload_sha256", models.CharField(max_length=64)),
                ("state", models.CharField(default="recorded", max_length=16)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="communications.logicalmessage",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SenderIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Correo"), ("whatsapp", "WhatsApp")], max_length=16
                    ),
                ),
                ("provider", models.CharField(max_length=32)),
                (
                    "ownership",
                    models.CharField(
                        choices=[("claridez", "Claridez"), ("organization", "Organización")],
                        max_length=16,
                    ),
                ),
                ("sender_reference", models.CharField(max_length=240)),
                ("display_name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("portal_authentication", "Autenticación Portal"),
                            ("capture_acknowledgement", "Acuse de captación"),
                            ("service_update", "Actualización de servicio"),
                            ("event_reminder", "Recordatorio de evento"),
                            ("payment_reminder", "Recordatorio de cobro"),
                            ("document_reminder", "Recordatorio documental"),
                            ("client_action", "Acción del cliente"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Correo"), ("whatsapp", "WhatsApp")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("approved", "Aprobada"),
                            ("disabled", "Deshabilitada"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("requires_consent", models.BooleanField(default=False)),
                ("allow_unsubscribe", models.BooleanField(default=False)),
                ("rationale", models.CharField(blank=True, max_length=500)),
                ("approved_by_membership_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "purpose", "channel", "version"),
                        name="communications_policy_version_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="communications_policy_version_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunicationPreferenceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("person_reference", models.UUIDField()),
                ("canonical_set", models.JSONField(default=list)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Correo"), ("whatsapp", "WhatsApp")], max_length=16
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("portal_authentication", "Autenticación Portal"),
                            ("capture_acknowledgement", "Acuse de captación"),
                            ("service_update", "Actualización de servicio"),
                            ("event_reminder", "Recordatorio de evento"),
                            ("payment_reminder", "Recordatorio de cobro"),
                            ("document_reminder", "Recordatorio documental"),
                            ("client_action", "Acción del cliente"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=32,
                    ),
                ),
                ("destination_fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("client_allow", "Permiso explícito del cliente"),
                            ("client_unsubscribe", "Baja del cliente"),
                            ("admin_suppress", "Supresión administrativa"),
                            ("admin_release", "Liberación administrativa"),
                            ("hard_bounce", "Rebote permanente"),
                            ("technical_release", "Liberación técnica probada"),
                        ],
                        max_length=24,
                    ),
                ),
                ("actor_membership_id", models.UUIDField(blank=True, null=True)),
                ("portal_principal_reference", models.UUIDField(blank=True, null=True)),
                ("evidence_sha256", models.CharField(blank=True, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("occurred_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"),
                        name="communications_preferenceevent_org_id_uq",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                action__in=["client_allow", "client_unsubscribe"],
                                actor_membership_id__isnull=True,
                                evidence_sha256__regex="^[0-9a-f]{64}$",
                                portal_principal_reference__isnull=False,
                            )
                            | models.Q(
                                action__in=["admin_suppress", "admin_release"],
                                actor_membership_id__isnull=False,
                                portal_principal_reference__isnull=True,
                            )
                            | models.Q(
                                action="hard_bounce",
                                actor_membership_id__isnull=True,
                                destination_fingerprint__regex="^[0-9a-f]{64}$",
                                evidence_sha256__regex="^[0-9a-f]{64}$",
                                portal_principal_reference__isnull=True,
                            )
                            | models.Q(
                                action="technical_release",
                                actor_membership_id__isnull=False,
                                destination_fingerprint__regex="^[0-9a-f]{64}$",
                                evidence_sha256__regex="^[0-9a-f]{64}$",
                                portal_principal_reference__isnull=True,
                            )
                        ),
                        name="communications_preference_actor_valid",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="communicationtemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="communications_template_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationtemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "name", "channel", "purpose"),
                name="communications_template_logical_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationtemplateversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="communications_templateversion_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationtemplateversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "template", "version"),
                name="communications_templateversion_number_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationtemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="communications_templateversion_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationintent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="communications_intent_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationintent",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="communications_intent_idempotency_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="logicalmessage",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="communications_message_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "message", "attempt"),
                name="communications_attempt_number_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="communicationoutbox",
            index=models.Index(
                fields=["organization", "state", "next_attempt_at", "created_at", "id"],
                name="comm_outbox_claim_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationoutbox",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="communications_outbox_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationoutbox",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1)),
                name="communications_outbox_attempts_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "provider", "provider_account", "provider_event_id"),
                name="communications_provider_event_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="senderidentity",
            constraint=models.UniqueConstraint(
                fields=("organization", "channel", "provider", "sender_reference"),
                name="communications_sender_identity_uq",
            ),
        ),
    ]
