# Generated by Django 5.2.17 on 2026-09-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0003_tenant_relation_integrity"),
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="communicationintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("causal_key", ""), _negated=True),
                    ("causal_sequence__isnull", False),
                ),
                fields=("organization", "causal_key", "causal_sequence"),
                name="communications_intent_causal_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="communicationintent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("causal_key", ""), ("causal_sequence__isnull", True)),
                    models.Q(
                        models.Q(("causal_key", ""), _negated=True),
                        ("causal_sequence__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="communications_intent_causal_pair_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="logicalmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_message_id", ""), _negated=True),
                fields=("organization", "provider", "provider_message_id"),
                name="communications_message_provider_id_uq",
            ),
        ),
    ]
