# Generated by Django 5.2.16 on 2026-08-12 18:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_venues_and_spaces"),
        ("scheduling", "0009_allow_terminal_operational_successors"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptanceChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hmac", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractualRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("root_reservation_id", models.UUIDField()),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_contractual_records",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractualInstrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("main_contract", "Contrato principal"),
                            ("addendum", "Adenda"),
                            ("termination", "Terminación"),
                            ("annex", "Anexo"),
                            ("other", "Otro aprobado"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierto"), ("closed", "Cerrado")],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_contractual_instruments",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instruments",
                        to="documents.contractualrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("render_issued_version", "Render de emisión"),
                            ("scan_external_file", "Análisis de archivo"),
                            ("verify_artifact", "Verificación de integridad"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("payload", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("correlation_id", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "En cola"),
                            ("running", "En ejecución"),
                            ("retry_wait", "Esperando reintento"),
                            ("succeeded", "Completado"),
                            ("dead", "Fallo terminal"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("next_attempt_at", models.DateTimeField()),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_by", models.CharField(blank=True, max_length=128)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("last_error_detail", models.CharField(blank=True, max_length=500)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentJobAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempt", models.PositiveSmallIntegerField()),
                ("worker_id", models.CharField(max_length=128)),
                ("outcome", models.CharField(max_length=24)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history",
                        to="documents.documentjob",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt", "started_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[("contractual", "Contractual")],
                        default="contractual",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicada"),
                            ("inactive", "Inactiva"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body_html", models.TextField()),
                ("variable_schema", models.JSONField(default=dict)),
                (
                    "variable_language_version",
                    models.CharField(default="claridez-vars-v1", max_length=24),
                ),
                ("source_sha256", models.CharField(max_length=64)),
                ("assets_manifest", models.JSONField(default=dict)),
                ("assets_sha256", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "published_by_membership",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_document_template_versions",
                        to="organizations.membership",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="documents.documenttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalAccessGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("read", "Lectura"),
                            ("download", "Descarga"),
                            ("accept", "Aceptación"),
                        ],
                        max_length=12,
                    ),
                ),
                ("token_hmac", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("max_exchanges", models.PositiveSmallIntegerField(default=1)),
                ("exchange_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_document_grants",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "revoked_by_membership",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalAccessEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=32)),
                ("result", models.CharField(max_length=24)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("request_id", models.CharField(blank=True, max_length=128)),
                ("detail", models.CharField(blank=True, max_length=300)),
                ("occurred_at", models.DateTimeField()),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.acceptancechallenge",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.externalaccessgrant",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="acceptancechallenge",
            name="grant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="documents.externalaccessgrant"
            ),
        ),
        migrations.CreateModel(
            name="ExternalDocumentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("token_hmac", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField()),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.externalaccessgrant",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("display_name", models.CharField(max_length=240)),
                ("storage_key", models.CharField(max_length=240, unique=True)),
                ("declared_media_type", models.CharField(max_length=80)),
                ("detected_media_type", models.CharField(blank=True, max_length=80)),
                ("extension", models.CharField(max_length=12)),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("uploading", "Subiendo"),
                            ("quarantined", "En cuarentena"),
                            ("pending_scan", "Pendiente de análisis"),
                            ("clean", "Limpio"),
                            ("infected", "Infectado"),
                            ("rejected", "Rechazado"),
                            ("scan_error", "Error de análisis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("validation_detail", models.CharField(blank=True, max_length=500)),
                ("available_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_files",
                        to="documents.contractualrecord",
                    ),
                ),
                (
                    "uploaded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_document_files",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalFileEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_state", models.CharField(blank=True, max_length=20)),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("uploading", "Subiendo"),
                            ("quarantined", "En cuarentena"),
                            ("pending_scan", "Pendiente de análisis"),
                            ("clean", "Limpio"),
                            ("infected", "Infectado"),
                            ("rejected", "Rechazado"),
                            ("scan_error", "Error de análisis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=80)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("occurred_at", models.DateTimeField()),
                (
                    "external_file",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.externalfile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExternalRateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key_hash", models.CharField(max_length=64)),
                ("window_start", models.DateTimeField()),
                ("request_count", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key_hash", "window_start"),
                        name="documents_ratelimit_key_window_uq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalTokenLocator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("session", "Sesión"),
                            ("challenge", "Challenge"),
                        ],
                        max_length=12,
                    ),
                ),
                ("token_hmac", models.CharField(max_length=64, unique=True)),
                ("organization_id", models.UUIDField()),
                ("target_id", models.UUIDField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "target_id"), name="documents_tokenlocator_kind_target_uq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GeneratedArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("storage_key", models.CharField(max_length=240, unique=True)),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("media_type", models.CharField(default="application/pdf", max_length=80)),
                ("provenance", models.JSONField()),
                ("renderer_name", models.CharField(max_length=64)),
                ("renderer_version", models.CharField(max_length=32)),
                ("render_environment", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("integrity_failed", "Integridad fallida"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("stored_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="externalaccessgrant",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="documents.generatedartifact"
            ),
        ),
        migrations.CreateModel(
            name="ArtifactIntegrityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("verified", "Verificado"),
                            ("mismatch", "No coincide"),
                            ("missing", "Ausente"),
                            ("error", "Error"),
                        ],
                        max_length=12,
                    ),
                ),
                ("expected_sha256", models.CharField(max_length=64)),
                ("observed_sha256", models.CharField(blank=True, max_length=64)),
                ("observed_size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("occurred_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.generatedartifact",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="acceptancechallenge",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="documents.generatedartifact"
            ),
        ),
        migrations.CreateModel(
            name="IssuedInstrumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                ("current_reservation_id", models.UUIDField()),
                ("quotation_version_id", models.UUIDField()),
                ("snapshot", models.JSONField()),
                ("snapshot_schema_version", models.CharField(max_length=32)),
                ("snapshot_sha256", models.CharField(max_length=64)),
                ("resolved_variables", models.JSONField()),
                ("provenance", models.JSONField()),
                ("materiality_policy_version", models.CharField(max_length=32)),
                ("renderer_name", models.CharField(max_length=64)),
                ("renderer_version", models.CharField(max_length=32)),
                ("render_environment", models.CharField(max_length=128)),
                ("assets_sha256", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_render", "Pendiente de render"),
                            ("rendering", "Renderizando"),
                            ("issued", "Emitida"),
                            ("render_failed", "Render fallido"),
                        ],
                        default="pending_render",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_versions",
                        to="documents.contractualinstrument",
                    ),
                ),
                (
                    "issued_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_contractual_versions",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.documenttemplateversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="generatedartifact",
            name="issued_version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifact",
                to="documents.issuedinstrumentversion",
            ),
        ),
        migrations.AddField(
            model_name="externalaccessgrant",
            name="issued_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="documents.issuedinstrumentversion"
            ),
        ),
        migrations.CreateModel(
            name="AcceptanceEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("artifact_sha256", models.CharField(max_length=64)),
                ("manifestation_text", models.TextField()),
                ("manifestation_version", models.CharField(max_length=32)),
                ("acceptor_projection", models.JSONField()),
                ("attribution_method", models.CharField(max_length=64)),
                ("authentication_result", models.JSONField()),
                ("mechanism_version", models.CharField(max_length=32)),
                ("accepted_at", models.DateTimeField()),
                ("timezone_name", models.CharField(max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("request_id", models.CharField(max_length=128)),
                ("correlation_id", models.CharField(max_length=128)),
                (
                    "challenge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.acceptancechallenge",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.generatedartifact",
                    ),
                ),
                (
                    "issued_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.issuedinstrumentversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="acceptancechallenge",
            name="issued_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="documents.issuedinstrumentversion"
            ),
        ),
        migrations.CreateModel(
            name="MalwareScanAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempt", models.PositiveIntegerField()),
                ("scanner_name", models.CharField(max_length=64)),
                ("scanner_version", models.CharField(blank=True, max_length=80)),
                ("signatures_version", models.CharField(blank=True, max_length=120)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("clean", "Limpio"),
                            ("infected", "Infectado"),
                            ("unsupported", "No soportado"),
                            ("timeout", "Timeout"),
                            ("technical_error", "Error técnico"),
                            ("incomplete", "Incompleto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("malware_name", models.CharField(blank=True, max_length=200)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "external_file",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scan_attempts",
                        to="documents.externalfile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt", "started_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RetentionAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("target_type", models.CharField(max_length=32)),
                ("target_id", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("retain", "Conservar"),
                            ("held", "Legal hold"),
                            ("eligible", "Elegible para disposición"),
                        ],
                        default="retain",
                        max_length=12,
                    ),
                ),
                ("eligible_at", models.DateTimeField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegalHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.CharField(max_length=500)),
                ("placed_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.CharField(blank=True, max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "placed_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placed_document_holds",
                        to="organizations.membership",
                    ),
                ),
                (
                    "released_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="released_document_holds",
                        to="organizations.membership",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.retentionassignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetentionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=32)),
                ("evidence", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.membership"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.retentionassignment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=80)),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=160)),
                ("classification", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("active", "Activa"),
                            ("retired", "Retirada"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("rules", models.JSONField(default=dict)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by_membership",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="retentionassignment",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="documents.retentionpolicy"
            ),
        ),
        migrations.CreateModel(
            name="TemplateEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("published", "Publicación"),
                            ("inactivated", "Inactivación"),
                            ("reactivated", "Reactivación"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "actor_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.documenttemplate",
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documents.documenttemplateversion",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="contractualrecord",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_record_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractualrecord",
            constraint=models.UniqueConstraint(
                fields=("organization", "root_reservation_id"), name="documents_record_org_root_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractualinstrument",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_instrument_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractualinstrument",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="documents_instrument_revision_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="documentjob",
            index=models.Index(
                fields=["organization", "state", "next_attempt_at"], name="documents_job_claim_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjob",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_job_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjob",
            constraint=models.UniqueConstraint(
                fields=("organization", "job_type", "idempotency_key"),
                name="documents_job_idempotency_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1)),
                name="documents_job_max_attempts_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempts__lte", models.F("max_attempts"))),
                name="documents_job_attempts_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjobattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_jobattempt_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentjobattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "job", "attempt"),
                name="documents_jobattempt_job_attempt_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_template_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="documents_template_org_name_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="documents_template_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplateversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_templateversion_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplateversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "template", "version"),
                name="documents_templateversion_org_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplateversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("organization", "template"),
                name="documents_templateversion_one_draft_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttemplateversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="documents_templateversion_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalaccessevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_accessevent_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="externaldocumentsession",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_externalsession_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalfile",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_externalfile_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalfile",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gt", 0)),
                name="documents_externalfile_size_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalfileevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_externalfileevent_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactintegrityevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_integrityevent_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="issuedinstrumentversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_issuedversion_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="issuedinstrumentversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "instrument", "version"),
                name="documents_issuedversion_org_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuedinstrumentversion",
            constraint=models.UniqueConstraint(
                fields=("organization", "idempotency_key"),
                name="documents_issuedversion_idempotency_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuedinstrumentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="documents_issuedversion_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_artifact_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gt", 0)), name="documents_artifact_size_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalaccessgrant",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_grant_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalaccessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_exchanges__gte", 1)),
                name="documents_grant_max_exchanges_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalaccessgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_count__lte", models.F("max_exchanges"))),
                name="documents_grant_exchange_count_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptanceevidence",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_acceptance_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptancechallenge",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_challenge_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="malwarescanattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_scanattempt_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="malwarescanattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "external_file", "attempt"),
                name="documents_scanattempt_file_attempt_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="malwarescanattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt__gte", 1)),
                name="documents_scanattempt_attempt_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="legalhold",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_legalhold_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="legalhold",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("organization", "assignment"),
                name="documents_legalhold_one_active_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_retentionevent_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionpolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_retentionpolicy_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionpolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "key", "version"),
                name="documents_retentionpolicy_key_version_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionassignment",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_retentionassignment_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="retentionassignment",
            constraint=models.UniqueConstraint(
                fields=("organization", "target_type", "target_id"),
                name="documents_retentionassignment_target_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="templateevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_templateevent_org_id_uq"
            ),
        ),
    ]
