# Generated by Django 5.2.16 on 2026-08-12 18:22

import django.db.models.deletion
from django.db import migrations, models

FORWARD_GUARD_SQL = r"""
CREATE OR REPLACE FUNCTION public.claridez_guard_generated_artifact_v2()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public AS $function$
BEGIN
    IF ROW(NEW.organization_id, NEW.issued_version_id, NEW.sequence,
           NEW.is_emitted_original, NEW.storage_key, NEW.sha256,
           NEW.size_bytes, NEW.media_type, NEW.provenance, NEW.renderer_name,
           NEW.renderer_version, NEW.render_environment, NEW.stored_at, NEW.created_at)
       IS DISTINCT FROM
       ROW(OLD.organization_id, OLD.issued_version_id, OLD.sequence,
           OLD.is_emitted_original, OLD.storage_key, OLD.sha256,
           OLD.size_bytes, OLD.media_type, OLD.provenance, OLD.renderer_name,
           OLD.renderer_version, OLD.render_environment, OLD.stored_at, OLD.created_at) THEN
        RAISE EXCEPTION 'artifact evidence is immutable' USING ERRCODE = '23514';
    END IF;
    IF OLD.state = 'integrity_failed' AND NEW IS DISTINCT FROM OLD THEN
        RAISE EXCEPTION 'failed artifact evidence is immutable' USING ERRCODE = '23514';
    END IF;
    IF NEW.state NOT IN ('available', 'integrity_failed') THEN
        RAISE EXCEPTION 'invalid artifact state' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END
$function$;
REVOKE ALL ON FUNCTION public.claridez_guard_generated_artifact_v2() FROM PUBLIC;
DROP TRIGGER IF EXISTS documents_generatedartifact_guard
    ON public.documents_generatedartifact;
CREATE TRIGGER documents_generatedartifact_guard
    BEFORE UPDATE ON public.documents_generatedartifact
    FOR EACH ROW EXECUTE FUNCTION public.claridez_guard_generated_artifact_v2();
"""

REVERSE_GUARD_SQL = r"""
DROP TRIGGER IF EXISTS documents_generatedartifact_guard
    ON public.documents_generatedartifact;
CREATE TRIGGER documents_generatedartifact_guard
    BEFORE UPDATE ON public.documents_generatedartifact
    FOR EACH ROW EXECUTE FUNCTION public.claridez_guard_document_version();
DROP FUNCTION IF EXISTS public.claridez_guard_generated_artifact_v2();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_tenant_security_integrity"),
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedartifact",
            name="is_emitted_original",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="generatedartifact",
            name="sequence",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="generatedartifact",
            name="issued_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="documents.issuedinstrumentversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedartifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="documents_artifact_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedartifact",
            constraint=models.UniqueConstraint(
                fields=("organization", "issued_version", "sequence"),
                name="documents_artifact_org_version_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="generatedartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_emitted_original", True)),
                fields=("organization", "issued_version"),
                name="documents_artifact_one_original_uq",
            ),
        ),
        migrations.RunSQL(FORWARD_GUARD_SQL, REVERSE_GUARD_SQL),
    ]
