# Generated by Django 5.2.16 on 2026-08-15 00:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_acceptance_privacy_and_no_delete_guards"),
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("finalize_external_upload", "Finalización de upload"),
                    ("finalize_domain_upload", "Finalización de upload de dominio"),
                    ("render_issued_version", "Render de emisión"),
                    ("render_domain_artifact", "Render de artefacto de dominio"),
                    ("scan_external_file", "Análisis de archivo"),
                    ("scan_domain_file", "Análisis de archivo de dominio"),
                    ("verify_artifact", "Verificación de integridad"),
                    ("verify_domain_artifact", "Verificación de artefacto de dominio"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PrivateDomainFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner_domain", models.CharField(max_length=32)),
                ("owner_id", models.UUIDField()),
                ("purpose", models.CharField(max_length=40)),
                ("display_name", models.CharField(max_length=240)),
                ("storage_key", models.CharField(max_length=240, unique=True)),
                ("declared_media_type", models.CharField(max_length=80)),
                ("detected_media_type", models.CharField(blank=True, max_length=80)),
                ("extension", models.CharField(max_length=12)),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("uploading", "Subiendo"),
                            ("quarantined", "En cuarentena"),
                            ("pending_scan", "Pendiente de análisis"),
                            ("clean", "Limpio"),
                            ("infected", "Infectado"),
                            ("rejected", "Rechazado"),
                            ("scan_error", "Error de análisis"),
                            ("integrity_failed", "Integridad fallida"),
                        ],
                        max_length=20,
                    ),
                ),
                ("validation_detail", models.CharField(blank=True, max_length=500)),
                ("available_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "uploaded_by_membership",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_private_domain_files",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivateDomainFileEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_state", models.CharField(blank=True, max_length=20)),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("uploading", "Subiendo"),
                            ("quarantined", "En cuarentena"),
                            ("pending_scan", "Pendiente de análisis"),
                            ("clean", "Limpio"),
                            ("infected", "Infectado"),
                            ("rejected", "Rechazado"),
                            ("scan_error", "Error de análisis"),
                            ("integrity_failed", "Integridad fallida"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=80)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("occurred_at", models.DateTimeField()),
                (
                    "domain_file",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="documents.privatedomainfile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PrivateDomainScanAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("attempt", models.PositiveIntegerField()),
                ("scanner_name", models.CharField(max_length=64)),
                ("scanner_version", models.CharField(blank=True, max_length=80)),
                ("signatures_version", models.CharField(blank=True, max_length=120)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("clean", "Limpio"),
                            ("infected", "Infectado"),
                            ("unsupported", "No soportado"),
                            ("timeout", "Timeout"),
                            ("technical_error", "Error técnico"),
                            ("incomplete", "Incompleto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("malware_name", models.CharField(blank=True, max_length=200)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "domain_file",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scan_attempts",
                        to="documents.privatedomainfile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedDomainArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner_domain", models.CharField(max_length=32)),
                ("owner_id", models.UUIDField()),
                ("purpose", models.CharField(max_length=40)),
                ("source_snapshot_sha256", models.CharField(max_length=64)),
                ("render_payload", models.JSONField()),
                (
                    "storage_key",
                    models.CharField(blank=True, max_length=240, null=True, unique=True),
                ),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("media_type", models.CharField(default="application/pdf", max_length=80)),
                ("renderer_name", models.CharField(blank=True, max_length=64)),
                ("renderer_version", models.CharField(blank=True, max_length=32)),
                ("render_environment", models.CharField(blank=True, max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_render", "Pendiente de render"),
                            ("available", "Disponible"),
                            ("render_failed", "Render fallido"),
                            ("integrity_failed", "Integridad fallida"),
                        ],
                        default="pending_render",
                        max_length=20,
                    ),
                ),
                ("stored_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "owner_domain", "owner_id"],
                        name="docs_domainartifact_owner_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "id"), name="documents_domainartifact_org_id_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("organization", "owner_domain", "owner_id", "purpose"),
                        name="documents_domainartifact_owner_purpose_uq",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="privatedomainfile",
            index=models.Index(
                fields=["organization", "owner_domain", "owner_id", "purpose"],
                name="documents_domainfile_owner_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="privatedomainfile",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_domainfile_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="privatedomainfile",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gt", 0)), name="documents_domainfile_size_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="privatedomainfileevent",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_domainfile_event_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="privatedomainscanattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="documents_domainscan_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="privatedomainscanattempt",
            constraint=models.UniqueConstraint(
                fields=("organization", "domain_file", "attempt"),
                name="documents_domainscan_attempt_uq",
            ),
        ),
    ]
