# Generated by Django 5.2.17 on 2026-09-01 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_domain_asset_security"),
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptanceevidence",
            name="portal_grant_reference",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acceptanceevidence",
            name="portal_idempotency_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acceptanceevidence",
            name="portal_principal_reference",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acceptanceevidence",
            name="provenance",
            field=models.CharField(
                choices=[
                    ("document_link", "Acceso documental P9"),
                    ("portal_session", "Sesión Portal P14"),
                ],
                default="document_link",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="acceptanceevidence",
            name="challenge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="documents.acceptancechallenge",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptanceevidence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("portal_idempotency_key__isnull", False)),
                fields=("organization", "portal_idempotency_key"),
                name="documents_acceptance_portal_idempotency_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="acceptanceevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("challenge__isnull", False),
                        ("portal_grant_reference__isnull", True),
                        ("portal_idempotency_key__isnull", True),
                        ("portal_principal_reference__isnull", True),
                        ("provenance", "document_link"),
                    ),
                    models.Q(
                        ("challenge__isnull", True),
                        ("portal_grant_reference__isnull", False),
                        ("portal_idempotency_key__isnull", False),
                        ("portal_principal_reference__isnull", False),
                        ("provenance", "portal_session"),
                    ),
                    _connector="OR",
                ),
                name="documents_acceptance_provenance_valid",
            ),
        ),
    ]
