# Generated by Django 5.2.17 on 2026-08-23 00:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_venues_and_spaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectCostPlanRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("root_reservation_id", models.UUIDField()),
                ("venue_id", models.UUIDField()),
                ("revision", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("reason", models.CharField(max_length=500)),
                ("published_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "published_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_cost_plans",
                        to="organizations.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["root_reservation_id", "revision", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[("variable", "Variable"), ("recurring", "Recurrente")],
                        max_length=12,
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[("manual", "Manual"), ("recurring", "Regla recurrente")],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("economic_date", models.DateField()),
                ("description", models.CharField(max_length=500)),
                ("evidence_reference", models.CharField(max_length=300)),
                ("recorded_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_expenses",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "scope",
                    models.CharField(
                        choices=[("business", "Negocio"), ("venue", "Sede"), ("event", "Evento")],
                        max_length=12,
                    ),
                ),
                ("root_reservation_id", models.UUIDField(blank=True, null=True)),
                ("venue_id", models.UUIDField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "expense_occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="finance.expenseoccurrence",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FinanceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("direct_cost", "Costo directo"),
                            ("variable_expense", "Gasto variable"),
                            ("recurring_expense", "Gasto recurrente"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("normalized_name", models.CharField(max_length=120)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_categories",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name", "id"],
            },
        ),
        migrations.AddField(
            model_name="expenseoccurrence",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finance.financecategory"
            ),
        ),
        migrations.CreateModel(
            name="DirectCostPlanLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("position", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=300)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="finance.directcostplanrevision",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.financecategory"
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="FinanceCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("command_type", models.CharField(max_length=48)),
                ("idempotency_key", models.UUIDField()),
                ("payload_sha256", models.CharField(max_length=64)),
                ("result_type", models.CharField(max_length=48)),
                ("result_reference", models.UUIDField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatingBudgetRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("venue_id", models.UUIDField(blank=True, null=True)),
                ("revision", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("reason", models.CharField(max_length=500)),
                ("published_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "published_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_budgets",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatingBudgetLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("position", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.financecategory"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "budget_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="finance.operatingbudgetrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalCostEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("root_reservation_id", models.UUIDField()),
                ("venue_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("economic_date", models.DateField()),
                ("description", models.CharField(max_length=500)),
                ("evidence_reference", models.CharField(max_length=300)),
                ("submitted_at", models.DateTimeField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.financecategory"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "submitted_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_cost_evidence",
                        to="organizations.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Aprobada"), ("rejected", "Rechazada")], max_length=12
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("decided_at", models.DateTimeField()),
                (
                    "decided_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_evidence_decisions",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "evidence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="finance.operationalcostevidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActualDirectCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("root_reservation_id", models.UUIDField()),
                ("venue_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("economic_date", models.DateField()),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("manual", "Registro manual"),
                            ("operations_evidence", "Evidencia de operaciones"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("evidence_reference", models.CharField(max_length=300)),
                ("recorded_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_direct_costs",
                        to="organizations.membership",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.financecategory"
                    ),
                ),
                (
                    "source_evidence",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actual_cost",
                        to="finance.operationalcostevidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationalPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(help_text="Límite exclusivo del periodo.")),
                ("label", models.CharField(max_length=80)),
                ("currency", models.CharField(max_length=3)),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_periods",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="OperatingCashMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("outflow", "Salida"), ("recovery", "Recuperación")], max_length=12
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("direct_cost", "Costo directo"), ("expense", "Gasto")],
                        max_length=16,
                    ),
                ),
                ("source_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("economic_date", models.DateField()),
                ("reason", models.CharField(max_length=500)),
                ("evidence_reference", models.CharField(max_length=300)),
                ("recorded_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "original_outflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recoveries",
                        to="finance.operatingcashmovement",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_cash_movements",
                        to="organizations.membership",
                    ),
                ),
                (
                    "registration_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_movements",
                        to="finance.operationalperiod",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="operatingbudgetrevision",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_revisions",
                to="finance.operationalperiod",
            ),
        ),
        migrations.CreateModel(
            name="ExpenseOccurrenceCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Aumenta"), ("decrease", "Disminuye")], max_length=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("economic_date", models.DateField()),
                (
                    "scope",
                    models.CharField(
                        choices=[("business", "Negocio"), ("venue", "Sede"), ("event", "Evento")],
                        max_length=12,
                    ),
                ),
                ("root_reservation_id", models.UUIDField(blank=True, null=True)),
                ("venue_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.CharField(max_length=500)),
                ("evidence_reference", models.CharField(max_length=300)),
                ("recorded_at", models.DateTimeField()),
                (
                    "expense_occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="finance.expenseoccurrence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_expense_corrections",
                        to="organizations.membership",
                    ),
                ),
                (
                    "registration_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_corrections",
                        to="finance.operationalperiod",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expenseoccurrence",
            name="registration_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expense_occurrences",
                to="finance.operationalperiod",
            ),
        ),
        migrations.CreateModel(
            name="DirectCostCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Aumenta"), ("decrease", "Disminuye")], max_length=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("economic_date", models.DateField()),
                ("reason", models.CharField(max_length=500)),
                ("evidence_reference", models.CharField(max_length=300)),
                ("recorded_at", models.DateTimeField()),
                (
                    "direct_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="finance.actualdirectcost",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_cost_corrections",
                        to="organizations.membership",
                    ),
                ),
                (
                    "registration_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_cost_corrections",
                        to="finance.operationalperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashMovementCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Aumenta"), ("decrease", "Disminuye")], max_length=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("economic_date", models.DateField()),
                ("reason", models.CharField(max_length=500)),
                ("recorded_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_cash_corrections",
                        to="organizations.membership",
                    ),
                ),
                (
                    "cash_movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="finance.operatingcashmovement",
                    ),
                ),
                (
                    "registration_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_corrections",
                        to="finance.operationalperiod",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actualdirectcost",
            name="registration_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="direct_costs",
                to="finance.operationalperiod",
            ),
        ),
        migrations.CreateModel(
            name="PeriodCloseSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("snapshot", models.JSONField()),
                ("snapshot_sha256", models.CharField(max_length=64)),
                ("receivables_cutoff_registered_at", models.DateTimeField()),
                ("receivables_source_count", models.PositiveIntegerField()),
                ("receivables_source_sha256", models.CharField(max_length=64)),
                ("closed_at", models.DateTimeField()),
                (
                    "closed_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_closes",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "period",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="close_snapshot",
                        to="finance.operationalperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecognitionAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("root_reservation_id", models.UUIDField()),
                ("venue_id", models.UUIDField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Aumenta"), ("decrease", "Disminuye")], max_length=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("economic_date", models.DateField()),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("measurement_correction", "Corrección de medición"),
                            ("omission_correction", "Corrección de omisión"),
                            ("duplicate_correction", "Corrección de duplicidad"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("evidence_reference", models.CharField(max_length=300)),
                ("recorded_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_recognition_adjustments",
                        to="organizations.membership",
                    ),
                ),
                (
                    "registration_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recognition_adjustments",
                        to="finance.operationalperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecognitionAdjustmentCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Aumenta"), ("decrease", "Disminuye")], max_length=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("economic_date", models.DateField()),
                ("reason", models.CharField(max_length=500)),
                ("recorded_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
                (
                    "recognition_adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="finance.recognitionadjustment",
                    ),
                ),
                (
                    "recorded_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_recognition_corrections",
                        to="organizations.membership",
                    ),
                ),
                (
                    "registration_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recognition_corrections",
                        to="finance.operationalperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringExpenseRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=160)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("day_of_month", models.PositiveSmallIntegerField()),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("default_venue_id", models.UUIDField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.financecategory"
                    ),
                ),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_recurring_rules",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expenseoccurrence",
            name="recurring_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="occurrences",
                to="finance.recurringexpenserule",
            ),
        ),
        migrations.AddConstraint(
            model_name="directcostplanrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_plan_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="directcostplanrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "root_reservation_id", "revision"),
                name="finance_plan_org_root_rev_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="directcostplanrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="finance_plan_revision_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseallocation",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_alloc_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseallocation",
            constraint=models.UniqueConstraint(
                fields=("organization", "expense_occurrence", "position"),
                name="finance_alloc_position_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_alloc_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("root_reservation_id__isnull", True),
                        ("scope", "business"),
                        ("venue_id__isnull", True),
                    ),
                    models.Q(
                        ("root_reservation_id__isnull", True),
                        ("scope", "venue"),
                        ("venue_id__isnull", False),
                    ),
                    models.Q(
                        ("root_reservation_id__isnull", False),
                        ("scope", "event"),
                        ("venue_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="finance_alloc_scope_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="financecategory",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_cat_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="financecategory",
            constraint=models.UniqueConstraint(
                fields=("organization", "kind", "normalized_name"),
                name="finance_cat_org_kind_name_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="directcostplanline",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_planline_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="directcostplanline",
            constraint=models.UniqueConstraint(
                fields=("organization", "plan_revision", "position"),
                name="finance_planline_position_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="directcostplanline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_planline_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="directcostplanline",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="finance_planline_position_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="financecommand",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_command_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="financecommand",
            constraint=models.UniqueConstraint(
                fields=("organization", "command_type", "idempotency_key"),
                name="finance_command_idempotency_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingbudgetline",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_budgetline_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingbudgetline",
            constraint=models.UniqueConstraint(
                fields=("organization", "budget_revision", "position"),
                name="finance_budgetline_position_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingbudgetline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_budgetline_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalcostevidence",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_evidence_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalcostevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_evidence_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencedecision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_decision_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidencedecision",
            constraint=models.UniqueConstraint(
                fields=("organization", "evidence"), name="finance_decision_evidence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalperiod",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_period_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalperiod",
            constraint=models.UniqueConstraint(
                fields=("organization", "starts_on"), name="finance_period_org_start_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operationalperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gt", models.F("starts_on"))),
                name="finance_period_range_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingcashmovement",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_cash_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingcashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_cash_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingcashmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("direction", "outflow"), ("original_outflow__isnull", True)),
                    models.Q(("direction", "recovery"), ("original_outflow__isnull", False)),
                    _connector="OR",
                ),
                name="finance_cash_direction_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingbudgetrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_budget_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingbudgetrevision",
            constraint=models.UniqueConstraint(
                fields=("organization", "period", "venue_id", "revision"),
                name="finance_budget_scope_rev_uq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingbudgetrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="finance_budget_revision_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseoccurrencecorrection",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_expcorr_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseoccurrencecorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_expcorr_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseoccurrencecorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("root_reservation_id__isnull", True),
                        ("scope", "business"),
                        ("venue_id__isnull", True),
                    ),
                    models.Q(
                        ("root_reservation_id__isnull", True),
                        ("scope", "venue"),
                        ("venue_id__isnull", False),
                    ),
                    models.Q(
                        ("root_reservation_id__isnull", False),
                        ("scope", "event"),
                        ("venue_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="finance_expcorr_scope_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="directcostcorrection",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_costcorr_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="directcostcorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_costcorr_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovementcorrection",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_cashcorr_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashmovementcorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_cashcorr_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="actualdirectcost",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_cost_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="actualdirectcost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_evidence__isnull", False)),
                fields=("organization", "source_evidence"),
                name="finance_cost_evidence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="actualdirectcost",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_cost_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="periodclosesnapshot",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_close_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="periodclosesnapshot",
            constraint=models.UniqueConstraint(
                fields=("organization", "period"), name="finance_close_org_period_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="recognitionadjustment",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_recognition_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="recognitionadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_recognition_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="recognitionadjustmentcorrection",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_reccorr_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="recognitionadjustmentcorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_reccorr_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpenserule",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_rule_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpenserule",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_rule_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpenserule",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_month__gte", 1), ("day_of_month__lte", 28)),
                name="finance_rule_day_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringexpenserule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="finance_rule_validity_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseoccurrence",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_expense_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseoccurrence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recurring_rule__isnull", False)),
                fields=("organization", "recurring_rule", "economic_date"),
                name="finance_expense_rule_date_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_expense_amount_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("provenance", "manual"), ("recurring_rule__isnull", True)),
                    models.Q(
                        ("expense_type", "recurring"),
                        ("provenance", "recurring"),
                        ("recurring_rule__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="finance_expense_provenance_ck",
            ),
        ),
    ]
