# ruff: noqa: E501
# Generated by Django 5.2.17 on 2026-08-23 09:03

import uuid

import django.db.models.deletion
from django.db import migrations, models

FORWARD_SQL = r"""
ALTER TABLE public.finance_financialsourcereference
ADD CONSTRAINT finance_source_receiptline_fk
FOREIGN KEY (organization_id, source_id)
REFERENCES public.resources_supplyreceiptline (organization_id, id)
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.finance_financialsourcereference
ADD CONSTRAINT finance_source_actual_fk
FOREIGN KEY (organization_id, actual_direct_cost_id)
REFERENCES public.finance_actualdirectcost (organization_id, id)
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.finance_financialsourcereference
ADD CONSTRAINT finance_source_expense_fk
FOREIGN KEY (organization_id, expense_occurrence_id)
REFERENCES public.finance_expenseoccurrence (organization_id, id)
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public.finance_financialsourcereference
ADD CONSTRAINT finance_source_actor_fk
FOREIGN KEY (organization_id, created_by_membership_id)
REFERENCES public.organizations_membership (organization_id, id)
DEFERRABLE INITIALLY DEFERRED;

CREATE OR REPLACE FUNCTION public.claridez_finance_check_resources_source(
    target_organization uuid, target_type text, target_id uuid
) RETURNS void LANGUAGE plpgsql SET search_path = pg_catalog, public AS $function$
DECLARE reference_count integer; source_row record; target_row record; category_kind text;
BEGIN
    IF target_type = 'actual_direct_cost' THEN
        SELECT * INTO target_row FROM public.finance_actualdirectcost
        WHERE organization_id = target_organization AND id = target_id;
        IF target_row.id IS NULL OR target_row.provenance <> 'resources_receipt' THEN RETURN; END IF;
        SELECT count(*) INTO reference_count
        FROM public.finance_financialsourcereference reference
        WHERE reference.organization_id = target_organization
          AND reference.target_kind = target_type
          AND actual_direct_cost_id = target_id;
        SELECT category.kind INTO category_kind
        FROM public.finance_financecategory category
        WHERE category.organization_id = target_organization AND category.id = target_row.category_id;
        IF category_kind <> 'direct_cost' THEN
            RAISE EXCEPTION 'resources direct cost category is incompatible' USING ERRCODE = '23514';
        END IF;
    ELSE
        SELECT * INTO target_row FROM public.finance_expenseoccurrence
        WHERE organization_id = target_organization AND id = target_id;
        IF target_row.id IS NULL OR target_row.provenance <> 'resources_receipt' THEN RETURN; END IF;
        SELECT count(*) INTO reference_count
        FROM public.finance_financialsourcereference reference
        WHERE reference.organization_id = target_organization
          AND reference.target_kind = target_type
          AND expense_occurrence_id = target_id;
        SELECT category.kind INTO category_kind
        FROM public.finance_financecategory category
        WHERE category.organization_id = target_organization AND category.id = target_row.category_id;
        IF target_row.recurring_rule_id IS NOT NULL
           OR (target_row.expense_type = 'variable' AND category_kind <> 'variable_expense')
           OR (target_row.expense_type = 'recurring' AND category_kind <> 'recurring_expense')
        THEN
            RAISE EXCEPTION 'resources expense type and category are incompatible' USING ERRCODE = '23514';
        END IF;
    END IF;
    IF reference_count <> 1 THEN
        RAISE EXCEPTION 'resources financial target requires exactly one source reference'
        USING ERRCODE = '23514';
    END IF;
    SELECT receipt.*,
           purchase.root_reservation_id AS purchase_root_reservation_id,
           purchase.venue_id AS purchase_venue_id
    INTO source_row
    FROM public.finance_financialsourcereference reference
    JOIN public.resources_supplyreceiptline receipt
      ON receipt.organization_id = reference.organization_id AND receipt.id = reference.source_id
    JOIN public.resources_supplyreceipt supply_receipt
      ON supply_receipt.organization_id = receipt.organization_id
     AND supply_receipt.id = receipt.receipt_id
    JOIN public.resources_purchase purchase
      ON purchase.organization_id = supply_receipt.organization_id
     AND purchase.id = supply_receipt.purchase_id
    WHERE reference.organization_id = target_organization
      AND (
        (target_type = 'actual_direct_cost' AND reference.actual_direct_cost_id = target_id)
        OR (target_type = 'expense_occurrence' AND reference.expense_occurrence_id = target_id)
      );
    IF source_row.id IS NULL OR source_row.kind NOT IN ('goods_received', 'service_fulfilled')
       OR source_row.confirmed_at IS NULL THEN
        RAISE EXCEPTION 'resources financial source is not a confirmed receipt line'
        USING ERRCODE = '23514';
    END IF;
    IF target_type = 'actual_direct_cost' THEN
        IF source_row.purchase_root_reservation_id IS NULL
           OR source_row.purchase_venue_id IS NULL
           OR target_row.root_reservation_id <> source_row.purchase_root_reservation_id
           OR target_row.venue_id <> source_row.purchase_venue_id
        THEN
            RAISE EXCEPTION 'resources direct cost does not match purchase event scope'
            USING ERRCODE = '23514';
        END IF;
    END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.claridez_finance_resources_source_guard()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public AS $function$
DECLARE previous_context text;
BEGIN
    previous_context := pg_catalog.current_setting('claridez.organization_id', true);
    PERFORM pg_catalog.set_config('claridez.organization_id', NEW.organization_id::text, true);
    BEGIN
        IF TG_TABLE_NAME = 'finance_financialsourcereference' THEN
            IF NEW.actual_direct_cost_id IS NOT NULL THEN
                PERFORM public.claridez_finance_check_resources_source(
                    NEW.organization_id, 'actual_direct_cost', NEW.actual_direct_cost_id
                );
            ELSE
                PERFORM public.claridez_finance_check_resources_source(
                    NEW.organization_id, 'expense_occurrence', NEW.expense_occurrence_id
                );
            END IF;
        ELSIF TG_TABLE_NAME = 'finance_actualdirectcost' THEN
            IF NEW.provenance = 'resources_receipt' THEN
                PERFORM public.claridez_finance_check_resources_source(
                    NEW.organization_id, 'actual_direct_cost', NEW.id
                );
            END IF;
        ELSIF TG_TABLE_NAME = 'finance_expenseoccurrence' THEN
            IF NEW.provenance = 'resources_receipt' THEN
                PERFORM public.claridez_finance_check_resources_source(
                    NEW.organization_id, 'expense_occurrence', NEW.id
                );
            END IF;
        END IF;
    EXCEPTION WHEN OTHERS THEN
        PERFORM pg_catalog.set_config(
            'claridez.organization_id', coalesce(previous_context, ''), true
        );
        RAISE;
    END;
    PERFORM pg_catalog.set_config(
        'claridez.organization_id', coalesce(previous_context, ''), true
    );
    RETURN NULL;
END;
$function$;

CREATE CONSTRAINT TRIGGER finance_source_reference_complete
AFTER INSERT ON public.finance_financialsourcereference DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION public.claridez_finance_resources_source_guard();
CREATE CONSTRAINT TRIGGER finance_resources_actual_complete
AFTER INSERT ON public.finance_actualdirectcost DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION public.claridez_finance_resources_source_guard();
CREATE CONSTRAINT TRIGGER finance_resources_expense_complete
AFTER INSERT ON public.finance_expenseoccurrence DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION public.claridez_finance_resources_source_guard();

CREATE OR REPLACE FUNCTION public.claridez_finance_source_immutable()
RETURNS trigger LANGUAGE plpgsql SET search_path = pg_catalog, public AS $function$
BEGIN
    RAISE EXCEPTION 'financial source reference is append-only' USING ERRCODE = '23514';
END;
$function$;
CREATE TRIGGER finance_source_reference_immutable
BEFORE UPDATE OR DELETE ON public.finance_financialsourcereference
FOR EACH ROW EXECUTE FUNCTION public.claridez_finance_source_immutable();

REVOKE ALL ON TABLE public.finance_financialsourcereference FROM PUBLIC, claridez_app;
GRANT SELECT, INSERT ON TABLE public.finance_financialsourcereference TO claridez_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.finance_financialsourcereference TO claridez_test_runner;
REVOKE DELETE, TRUNCATE ON TABLE public.finance_financialsourcereference FROM claridez_app;
ALTER TABLE public.finance_financialsourcereference ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finance_financialsourcereference FORCE ROW LEVEL SECURITY;
CREATE POLICY finance_financialsourcereference_tenant_policy
ON public.finance_financialsourcereference AS PERMISSIVE FOR ALL
USING (organization_id = public.claridez_current_organization_id())
WITH CHECK (organization_id = public.claridez_current_organization_id());
"""

REVERSE_SQL = r"""
DROP POLICY IF EXISTS finance_financialsourcereference_tenant_policy
ON public.finance_financialsourcereference;
ALTER TABLE public.finance_financialsourcereference NO FORCE ROW LEVEL SECURITY;
ALTER TABLE public.finance_financialsourcereference DISABLE ROW LEVEL SECURITY;
DROP TRIGGER IF EXISTS finance_source_reference_immutable ON public.finance_financialsourcereference;
DROP FUNCTION IF EXISTS public.claridez_finance_source_immutable();
DROP TRIGGER IF EXISTS finance_resources_expense_complete ON public.finance_expenseoccurrence;
DROP TRIGGER IF EXISTS finance_resources_actual_complete ON public.finance_actualdirectcost;
DROP TRIGGER IF EXISTS finance_source_reference_complete ON public.finance_financialsourcereference;
DROP FUNCTION IF EXISTS public.claridez_finance_resources_source_guard();
DROP FUNCTION IF EXISTS public.claridez_finance_check_resources_source(uuid, text, uuid);
ALTER TABLE public.finance_financialsourcereference DROP CONSTRAINT IF EXISTS finance_source_actor_fk;
ALTER TABLE public.finance_financialsourcereference DROP CONSTRAINT IF EXISTS finance_source_expense_fk;
ALTER TABLE public.finance_financialsourcereference DROP CONSTRAINT IF EXISTS finance_source_actual_fk;
ALTER TABLE public.finance_financialsourcereference DROP CONSTRAINT IF EXISTS finance_source_receiptline_fk;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_baseline_and_expense_cash_attribution"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialSourceReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_kind", models.CharField(default="resources_receipt_line", max_length=32)),
                ("source_id", models.UUIDField()),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("actual_direct_cost", "Costo directo real"),
                            ("expense_occurrence", "Ocurrencia de gasto"),
                        ],
                        max_length=24,
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="expenseoccurrence",
            name="finance_expense_provenance_ck",
        ),
        migrations.AlterField(
            model_name="actualdirectcost",
            name="provenance",
            field=models.CharField(
                choices=[
                    ("manual", "Registro manual"),
                    ("operations_evidence", "Evidencia de operaciones"),
                    ("resources_receipt", "Recepción P12"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="expenseoccurrence",
            name="provenance",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("recurring", "Regla recurrente"),
                    ("resources_receipt", "Recepción P12"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("provenance", "manual"), ("recurring_rule__isnull", True)),
                    models.Q(
                        ("expense_type", "recurring"),
                        ("provenance", "recurring"),
                        ("recurring_rule__isnull", False),
                    ),
                    models.Q(
                        ("expense_type__in", ["variable", "recurring"]),
                        ("provenance", "resources_receipt"),
                        ("recurring_rule__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="finance_expense_provenance_ck",
            ),
        ),
        migrations.AddField(
            model_name="financialsourcereference",
            name="actual_direct_cost",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resources_source_reference",
                to="finance.actualdirectcost",
            ),
        ),
        migrations.AddField(
            model_name="financialsourcereference",
            name="created_by_membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_source_references",
                to="organizations.membership",
            ),
        ),
        migrations.AddField(
            model_name="financialsourcereference",
            name="expense_occurrence",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resources_source_reference",
                to="finance.expenseoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="financialsourcereference",
            name="organization",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialsourcereference",
            constraint=models.UniqueConstraint(
                fields=("organization", "id"), name="finance_source_org_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="financialsourcereference",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_kind", "source_id"),
                name="finance_source_receipt_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialsourcereference",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_kind", "resources_receipt_line")),
                name="finance_source_kind_resources_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="financialsourcereference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actual_direct_cost__isnull", False),
                        ("expense_occurrence__isnull", True),
                        ("target_kind", "actual_direct_cost"),
                    ),
                    models.Q(
                        ("actual_direct_cost__isnull", True),
                        ("expense_occurrence__isnull", False),
                        ("target_kind", "expense_occurrence"),
                    ),
                    _connector="OR",
                ),
                name="finance_source_exact_target_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="actualdirectcost",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("provenance", "manual"), ("source_evidence__isnull", True)),
                    models.Q(
                        ("provenance", "operations_evidence"), ("source_evidence__isnull", False)
                    ),
                    models.Q(
                        ("provenance", "resources_receipt"), ("source_evidence__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="finance_cost_provenance_ck",
            ),
        ),
        migrations.RunSQL(FORWARD_SQL, REVERSE_SQL),
    ]
